-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lz4CompressEngineRun_lzBestMatchFilter_6_65536_Pipeline_lz_bestMatchFilter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    compressdStream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    compressdStream_empty_n : IN STD_LOGIC;
    compressdStream_read : OUT STD_LOGIC;
    compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    bestMatchStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    bestMatchStream_full_n : IN STD_LOGIC;
    bestMatchStream_write : OUT STD_LOGIC;
    bestMatchStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    bestMatchStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    compare_window_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    compare_window_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    compare_window_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    compare_window_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    compare_window_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    compare_window : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    compare_window_12_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    compare_window_12_out_ap_vld : OUT STD_LOGIC;
    compare_window_13_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    compare_window_13_out_ap_vld : OUT STD_LOGIC;
    compare_window_14_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    compare_window_14_out_ap_vld : OUT STD_LOGIC;
    compare_window_15_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    compare_window_15_out_ap_vld : OUT STD_LOGIC;
    compare_window_16_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    compare_window_16_out_ap_vld : OUT STD_LOGIC;
    compare_window_17_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    compare_window_17_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of lz4CompressEngineRun_lzBestMatchFilter_6_65536_Pipeline_lz_bestMatchFilter is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_const_lv9_3 : STD_LOGIC_VECTOR (8 downto 0) := "000000011";
    constant ap_const_lv9_4 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_const_lv9_5 : STD_LOGIC_VECTOR (8 downto 0) := "000000101";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln339_fu_273_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal compressdStream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln339_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal bestMatchStream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal compare_window_15_reg_605 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal compare_window_14_reg_611 : STD_LOGIC_VECTOR (31 downto 0);
    signal compare_window_13_reg_616 : STD_LOGIC_VECTOR (31 downto 0);
    signal compare_window_12_reg_621 : STD_LOGIC_VECTOR (31 downto 0);
    signal compare_window_11_reg_626 : STD_LOGIC_VECTOR (31 downto 0);
    signal outValue_load_reg_635 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal best_match_1_fu_513_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal best_match_1_reg_641 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal i_9_fu_278_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal outValue_fu_94 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal compareValue_fu_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compareValue_1_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compareValue_2_fu_106 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compareValue_3_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal compareValue_4_fu_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage1_01001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal match_length_fu_312_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln365_fu_320_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal compareLen_1_fu_331_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal compareLen_2_fu_348_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal compareLen_3_fu_365_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal compareLen_4_fu_382_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal compareLen_5_fu_399_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal compareLen_fu_324_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln374_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln368_fu_338_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln365_1_fu_344_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln374_1_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln368_1_fu_355_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln365_2_fu_361_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln374_2_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln368_2_fu_372_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln365_3_fu_378_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln374_3_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln368_3_fu_389_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln365_4_fu_395_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln374_4_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln368_4_fu_407_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln374_fu_413_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln374_5_fu_477_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln374_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln374_1_fu_447_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_fu_489_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal best_match_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln374_3_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln374_4_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_2_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln374_2_fu_459_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_3_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln374_1_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal outValue_4_fu_528_p5 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_434 : BOOLEAN;
    signal ap_condition_438 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component lz4CompressEngineRun_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component lz4CompressEngineRun_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    compareValue_1_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                compareValue_1_fu_102 <= compare_window_2;
            elsif (((icmp_ln339_fu_273_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                compareValue_1_fu_102 <= compareValue_2_fu_106;
            end if; 
        end if;
    end process;

    compareValue_2_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                compareValue_2_fu_106 <= compare_window_3;
            elsif (((icmp_ln339_fu_273_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                compareValue_2_fu_106 <= compareValue_3_fu_110;
            end if; 
        end if;
    end process;

    compareValue_3_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                compareValue_3_fu_110 <= compare_window_4;
            elsif (((icmp_ln339_fu_273_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                compareValue_3_fu_110 <= compareValue_4_fu_114;
            end if; 
        end if;
    end process;

    compareValue_4_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_438)) then 
                    compareValue_4_fu_114 <= compare_window_5;
                elsif ((ap_const_boolean_1 = ap_condition_434)) then 
                    compareValue_4_fu_114 <= compressdStream_dout;
                end if;
            end if; 
        end if;
    end process;

    compareValue_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                compareValue_fu_98 <= compare_window_1;
            elsif (((icmp_ln339_fu_273_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                compareValue_fu_98 <= compareValue_1_fu_102;
            end if; 
        end if;
    end process;

    i_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                i_fu_90 <= ap_const_lv32_6;
            elsif (((icmp_ln339_fu_273_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                i_fu_90 <= i_9_fu_278_p2;
            end if; 
        end if;
    end process;

    outValue_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    outValue_fu_94 <= compare_window;
                elsif (((icmp_ln339_reg_631 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    outValue_fu_94 <= compare_window_15_reg_605;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                best_match_1_reg_641 <= best_match_1_fu_513_p2;
                outValue_load_reg_635 <= outValue_fu_94;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                compare_window_11_reg_626 <= compareValue_4_fu_114;
                compare_window_12_reg_621 <= compareValue_3_fu_110;
                compare_window_13_reg_616 <= compareValue_2_fu_106;
                compare_window_14_reg_611 <= compareValue_1_fu_102;
                compare_window_15_reg_605 <= compareValue_fu_98;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                icmp_ln339_reg_631 <= icmp_ln339_fu_273_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln368_1_fu_355_p2 <= std_logic_vector(unsigned(zext_ln365_fu_320_p1) + unsigned(ap_const_lv9_2));
    add_ln368_2_fu_372_p2 <= std_logic_vector(unsigned(zext_ln365_fu_320_p1) + unsigned(ap_const_lv9_3));
    add_ln368_3_fu_389_p2 <= std_logic_vector(unsigned(zext_ln365_fu_320_p1) + unsigned(ap_const_lv9_4));
    add_ln368_4_fu_407_p2 <= std_logic_vector(unsigned(zext_ln365_fu_320_p1) + unsigned(ap_const_lv9_5));
    add_ln368_fu_338_p2 <= std_logic_vector(unsigned(zext_ln365_fu_320_p1) + unsigned(ap_const_lv9_1));
    and_ln374_1_fu_495_p2 <= (best_match_fu_423_p2 and and_ln374_fu_489_p2);
    and_ln374_2_fu_501_p2 <= (xor_ln374_4_fu_483_p2 and xor_ln374_3_fu_471_p2);
    and_ln374_3_fu_507_p2 <= (xor_ln374_2_fu_459_p2 and and_ln374_2_fu_501_p2);
    and_ln374_fu_489_p2 <= (xor_ln374_fu_435_p2 and xor_ln374_1_fu_447_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter1, bestMatchStream_full_n)
    begin
                ap_block_pp0_stage1_01001 <= ((bestMatchStream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_01001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, bestMatchStream_full_n)
    begin
                ap_block_pp0_stage1_01001_grp2 <= ((bestMatchStream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, bestMatchStream_full_n)
    begin
                ap_block_pp0_stage1_11001 <= ((bestMatchStream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, bestMatchStream_full_n)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((bestMatchStream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, bestMatchStream_full_n)
    begin
                ap_block_pp0_stage1_subdone <= ((bestMatchStream_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_grp1_assign_proc : process(compressdStream_empty_n, icmp_ln339_reg_631)
    begin
                ap_block_state3_pp0_stage0_iter1_grp1 <= ((icmp_ln339_reg_631 = ap_const_lv1_1) and (compressdStream_empty_n = ap_const_logic_0));
    end process;


    ap_condition_434_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln339_reg_631, ap_block_pp0_stage0_11001_grp1)
    begin
                ap_condition_434 <= ((icmp_ln339_reg_631 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_438_assign_proc : process(ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_loop_init)
    begin
                ap_condition_438 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_loop_init = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln339_fu_273_p2)
    begin
        if (((icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    bestMatchStream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, bestMatchStream_full_n, ap_block_pp0_stage1_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bestMatchStream_blk_n <= bestMatchStream_full_n;
        else 
            bestMatchStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bestMatchStream_din <= 
        outValue_load_reg_635 when (best_match_1_reg_641(0) = '1') else 
        outValue_4_fu_528_p5;

    bestMatchStream_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bestMatchStream_write <= ap_const_logic_1;
        else 
            bestMatchStream_write <= ap_const_logic_0;
        end if; 
    end process;

    best_match_1_fu_513_p2 <= (and_ln374_3_fu_507_p2 and and_ln374_1_fu_495_p2);
    best_match_fu_423_p2 <= (icmp_ln374_fu_417_p2 xor ap_const_lv1_1);
    compareLen_1_fu_331_p3 <= compare_window_14_reg_611(15 downto 8);
    compareLen_2_fu_348_p3 <= compare_window_13_reg_616(15 downto 8);
    compareLen_3_fu_365_p3 <= compare_window_12_reg_621(15 downto 8);
    compareLen_4_fu_382_p3 <= compare_window_11_reg_626(15 downto 8);
    compareLen_5_fu_399_p3 <= compressdStream_dout(15 downto 8);
    compareLen_fu_324_p3 <= compare_window_15_reg_605(15 downto 8);
    compare_window_12_out <= compareValue_4_fu_114;

    compare_window_12_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln339_fu_273_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            compare_window_12_out_ap_vld <= ap_const_logic_1;
        else 
            compare_window_12_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    compare_window_13_out <= compareValue_3_fu_110;

    compare_window_13_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln339_fu_273_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            compare_window_13_out_ap_vld <= ap_const_logic_1;
        else 
            compare_window_13_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    compare_window_14_out <= compareValue_2_fu_106;

    compare_window_14_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln339_fu_273_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            compare_window_14_out_ap_vld <= ap_const_logic_1;
        else 
            compare_window_14_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    compare_window_15_out <= compareValue_1_fu_102;

    compare_window_15_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln339_fu_273_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            compare_window_15_out_ap_vld <= ap_const_logic_1;
        else 
            compare_window_15_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    compare_window_16_out <= compareValue_fu_98;

    compare_window_16_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln339_fu_273_p2, ap_loop_exit_ready, ap_block_pp0_stage1_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            compare_window_16_out_ap_vld <= ap_const_logic_1;
        else 
            compare_window_16_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    compare_window_17_out <= outValue_fu_94;

    compare_window_17_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage1, icmp_ln339_fu_273_p2, ap_loop_exit_ready, ap_block_pp0_stage1_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln339_fu_273_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            compare_window_17_out_ap_vld <= ap_const_logic_1;
        else 
            compare_window_17_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    compressdStream_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, compressdStream_empty_n, ap_block_pp0_stage0_grp1, icmp_ln339_reg_631)
    begin
        if (((icmp_ln339_reg_631 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            compressdStream_blk_n <= compressdStream_empty_n;
        else 
            compressdStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    compressdStream_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln339_reg_631, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((icmp_ln339_reg_631 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            compressdStream_read <= ap_const_logic_1;
        else 
            compressdStream_read <= ap_const_logic_0;
        end if; 
    end process;

    i_9_fu_278_p2 <= std_logic_vector(unsigned(i_fu_90) + unsigned(ap_const_lv32_1));
    icmp_ln339_fu_273_p2 <= "1" when (unsigned(i_fu_90) < unsigned(input_size_2)) else "0";
    icmp_ln374_1_fu_429_p2 <= "1" when (unsigned(add_ln368_fu_338_p2) < unsigned(zext_ln365_1_fu_344_p1)) else "0";
    icmp_ln374_2_fu_441_p2 <= "1" when (unsigned(add_ln368_1_fu_355_p2) < unsigned(zext_ln365_2_fu_361_p1)) else "0";
    icmp_ln374_3_fu_453_p2 <= "1" when (unsigned(add_ln368_2_fu_372_p2) < unsigned(zext_ln365_3_fu_378_p1)) else "0";
    icmp_ln374_4_fu_465_p2 <= "1" when (unsigned(add_ln368_3_fu_389_p2) < unsigned(zext_ln365_4_fu_395_p1)) else "0";
    icmp_ln374_5_fu_477_p2 <= "1" when (unsigned(add_ln368_4_fu_407_p2) < unsigned(zext_ln374_fu_413_p1)) else "0";
    icmp_ln374_fu_417_p2 <= "1" when (unsigned(match_length_fu_312_p3) < unsigned(compareLen_fu_324_p3)) else "0";
    match_length_fu_312_p3 <= outValue_fu_94(15 downto 8);
    outValue_4_fu_528_p5 <= (ap_const_lv24_0 & outValue_load_reg_635(7 downto 0));
    xor_ln374_1_fu_447_p2 <= (icmp_ln374_2_fu_441_p2 xor ap_const_lv1_1);
    xor_ln374_2_fu_459_p2 <= (icmp_ln374_3_fu_453_p2 xor ap_const_lv1_1);
    xor_ln374_3_fu_471_p2 <= (icmp_ln374_4_fu_465_p2 xor ap_const_lv1_1);
    xor_ln374_4_fu_483_p2 <= (icmp_ln374_5_fu_477_p2 xor ap_const_lv1_1);
    xor_ln374_fu_435_p2 <= (icmp_ln374_1_fu_429_p2 xor ap_const_lv1_1);
    zext_ln365_1_fu_344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(compareLen_1_fu_331_p3),9));
    zext_ln365_2_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(compareLen_2_fu_348_p3),9));
    zext_ln365_3_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(compareLen_3_fu_365_p3),9));
    zext_ln365_4_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(compareLen_4_fu_382_p3),9));
    zext_ln365_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(match_length_fu_312_p3),9));
    zext_ln374_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(compareLen_5_fu_399_p3),9));
end behav;
