// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lz4CompressEngineRun_lz4CompressPart2_Pipeline_lz4_compress (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        lit_outStream_dout,
        lit_outStream_empty_n,
        lit_outStream_read,
        lit_outStream_num_data_valid,
        lit_outStream_fifo_cap,
        lz4Out_din,
        lz4Out_full_n,
        lz4Out_write,
        lz4Out_eos_din,
        lz4Out_eos_full_n,
        lz4Out_eos_write,
        lenOffset_Stream_dout,
        lenOffset_Stream_empty_n,
        lenOffset_Stream_read,
        lenOffset_Stream_num_data_valid,
        lenOffset_Stream_fifo_cap,
        input_size_4,
        compressedSize_out,
        compressedSize_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] lit_outStream_dout;
input   lit_outStream_empty_n;
output   lit_outStream_read;
input  [12:0] lit_outStream_num_data_valid;
input  [12:0] lit_outStream_fifo_cap;
output  [7:0] lz4Out_din;
input   lz4Out_full_n;
output   lz4Out_write;
output  [0:0] lz4Out_eos_din;
input   lz4Out_eos_full_n;
output   lz4Out_eos_write;
input  [63:0] lenOffset_Stream_dout;
input   lenOffset_Stream_empty_n;
output   lenOffset_Stream_read;
input  [5:0] lenOffset_Stream_num_data_valid;
input  [5:0] lenOffset_Stream_fifo_cap;
input  [31:0] input_size_4;
output  [31:0] compressedSize_out;
output   compressedSize_out_ap_vld;

reg ap_idle;
reg lit_outStream_read;
reg lz4Out_write;
reg lz4Out_eos_write;
reg lenOffset_Stream_read;
reg compressedSize_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] or_ln182_reg_1073;
reg   [0:0] readOffsetFlag_3_reg_1068;
reg    ap_predicate_op56_read_state3;
reg    ap_block_state3_pp0_stage2_iter0_grp1;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage2_subdone;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    lenOffset_Stream_blk_n;
wire    ap_block_pp0_stage2_grp1;
reg    lit_outStream_blk_n;
wire    ap_block_pp0_stage0_grp2;
reg   [31:0] next_state_load_reg_1086;
reg    ap_block_pp0_stage0_subdone_grp2_done_reg;
reg    ap_block_pp0_stage0_subdone_grp2;
reg    ap_block_pp0_stage0_subdone;
reg    lz4Out_blk_n;
reg   [0:0] should_write_reg_1082;
reg    lz4Out_eos_blk_n;
wire    ap_block_pp0_stage0_grp3;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
reg    ap_block_state4_pp0_stage0_iter1_grp2;
reg    ap_block_pp0_stage0_11001_grp2;
reg   [31:0] inIdx_2_reg_1063;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire   [0:0] or_ln182_fu_340_p2;
reg   [31:0] compressedSize_1_reg_1077;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
wire   [0:0] should_write_fu_350_p2;
reg    ap_block_state4_pp0_stage0_iter1_grp3;
reg   [7:0] ap_phi_mux_outValue_11_phi_fu_223_p14;
wire   [7:0] outValue_10_fu_506_p3;
wire   [7:0] ap_phi_reg_pp0_iter1_outValue_11_reg_220;
wire   [7:0] outValue_8_fu_599_p1;
wire   [7:0] outValue_6_fu_683_p3;
wire   [7:0] outValue_fu_805_p3;
reg   [31:0] inIdx_fu_112;
wire   [31:0] inIdx_4_fu_754_p3;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire    ap_block_pp0_stage1;
reg   [0:0] readOffsetFlag_1_fu_116;
wire   [0:0] lit_ending_fu_767_p2;
reg   [0:0] extra_match_len_fu_120;
reg   [15:0] lit_length_fu_124;
wire   [15:0] lit_length_6_fu_698_p3;
wire   [15:0] lit_length_4_fu_828_p3;
reg   [15:0] match_length_fu_128;
wire   [15:0] match_length_16_fu_532_p3;
wire   [15:0] match_length_14_fu_868_p3;
reg   [15:0] write_lit_length_fu_132;
wire   [15:0] write_lit_length_2_fu_617_p2;
wire   [15:0] lit_length_7_fu_729_p1;
reg   [31:0] next_state_fu_136;
wire   [31:0] select_ln153_fu_540_p3;
wire   [31:0] select_ln330_fu_575_p3;
wire   [31:0] zext_ln151_fu_651_p1;
wire   [31:0] select_ln152_fu_706_p3;
wire   [31:0] zext_ln269_fu_858_p1;
wire    ap_block_pp0_stage2_grp0;
reg   [0:0] readOffsetFlag_fu_140;
wire   [0:0] readOffsetFlag_8_fu_527_p2;
wire   [0:0] readOffsetFlag_7_fu_583_p2;
wire   [0:0] readOffsetFlag_6_fu_637_p2;
reg   [0:0] is_special_end_fu_144;
wire   [0:0] is_special_end_1_fu_387_p2;
reg    ap_block_pp0_stage2_11001_grp1;
reg   [0:0] is_normal_end_fu_148;
wire   [0:0] is_normal_end_1_fu_399_p2;
reg   [0:0] lit_len_ge_15_fu_152;
wire   [0:0] lit_len_ge_15_1_fu_405_p2;
reg   [0:0] lit_len_gt_0_fu_156;
wire   [0:0] lit_len_gt_0_1_fu_411_p2;
reg   [0:0] match_len_ge_15_fu_160;
wire   [0:0] match_len_ge_15_1_fu_417_p2;
reg   [31:0] compressedSize_fu_164;
wire   [31:0] compressedSize_2_fu_916_p2;
reg   [15:0] match_len_tmp_fu_168;
wire   [15:0] match_len_tmp_1_fu_363_p1;
reg   [31:0] lit_len_tmp_fu_172;
wire   [31:0] lit_len_tmp_1_fu_355_p3;
reg   [15:0] match_offset_plus_one_fu_176;
wire   [15:0] match_offset_plus_one_1_fu_423_p2;
reg    ap_block_pp0_stage0_01001_grp2;
reg    ap_block_pp0_stage0_01001_grp3;
reg    ap_block_pp0_stage0_11001_grp3;
wire    ap_block_pp0_stage2_01001_grp0;
wire   [0:0] icmp_ln182_fu_329_p2;
wire   [0:0] xor_ln182_fu_334_p2;
wire   [15:0] match_off_tmp_fu_367_p3;
wire   [0:0] icmp_ln201_fu_375_p2;
wire   [0:0] icmp_ln201_1_fu_381_p2;
wire   [15:0] or_ln202_fu_393_p2;
wire   [0:0] match_len_ge_255_fu_496_p2;
wire   [7:0] trunc_ln336_fu_502_p1;
wire   [0:0] xor_ln338_fu_521_p2;
wire   [15:0] match_length_15_fu_515_p2;
wire   [0:0] icmp_ln310_fu_623_p2;
wire   [2:0] next_state_2_fu_629_p3;
wire   [2:0] next_state_3_fu_643_p3;
wire   [0:0] lit_len_ge_255_fu_673_p2;
wire   [7:0] trunc_ln295_fu_679_p1;
wire   [15:0] lit_length_5_fu_692_p2;
wire   [15:0] add_ln228_fu_733_p2;
wire   [15:0] sum_with_4_low_fu_739_p2;
wire   [31:0] zext_ln237_fu_745_p1;
wire   [31:0] inIdx_3_fu_749_p2;
wire   [0:0] or_ln246_fu_761_p2;
wire   [3:0] trunc_ln256_fu_773_p1;
wire   [3:0] lit_token_fu_777_p3;
wire   [3:0] match_token_fu_793_p1;
wire   [3:0] lit_token_1_fu_785_p3;
wire   [3:0] match_token_1_fu_797_p3;
wire   [15:0] lit_length_2_fu_814_p2;
wire   [15:0] lit_length_3_fu_820_p3;
wire   [0:0] or_ln270_fu_844_p2;
wire   [2:0] select_ln270_1_fu_836_p3;
wire   [2:0] next_state_tmp_fu_850_p3;
wire   [15:0] match_length_13_fu_862_p2;
wire    ap_block_pp0_stage0_grp0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_711;
reg    ap_condition_149;
reg    ap_condition_721;
reg    ap_condition_725;
reg    ap_condition_730;
reg    ap_condition_733;
reg    ap_condition_737;
reg    ap_condition_740;
reg    ap_condition_743;
reg    ap_condition_746;
reg    ap_condition_749;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 inIdx_fu_112 = 32'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 readOffsetFlag_1_fu_116 = 1'd0;
#0 extra_match_len_fu_120 = 1'd0;
#0 lit_length_fu_124 = 16'd0;
#0 match_length_fu_128 = 16'd0;
#0 write_lit_length_fu_132 = 16'd0;
#0 next_state_fu_136 = 32'd0;
#0 readOffsetFlag_fu_140 = 1'd0;
#0 is_special_end_fu_144 = 1'd0;
#0 is_normal_end_fu_148 = 1'd0;
#0 lit_len_ge_15_fu_152 = 1'd0;
#0 lit_len_gt_0_fu_156 = 1'd0;
#0 match_len_ge_15_fu_160 = 1'd0;
#0 compressedSize_fu_164 = 32'd0;
#0 match_len_tmp_fu_168 = 16'd0;
#0 lit_len_tmp_fu_172 = 32'd0;
#0 match_offset_plus_one_fu_176 = 16'd0;
#0 ap_done_reg = 1'b0;
end

lz4CompressEngineRun_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp2)) begin
                ap_block_pp0_stage0_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_exit_pp0_iter0_stage2) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_711)) begin
        if ((ap_loop_init == 1'b1)) begin
            compressedSize_fu_164 <= 32'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (should_write_reg_1082 == 1'd1))) begin
            compressedSize_fu_164 <= compressedSize_2_fu_916_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            extra_match_len_fu_120 <= 1'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0))) begin
            extra_match_len_fu_120 <= match_len_ge_15_fu_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_725)) begin
            inIdx_fu_112 <= 32'd0;
        end else if ((1'b1 == ap_condition_721)) begin
            inIdx_fu_112 <= inIdx_4_fu_754_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        is_normal_end_fu_148 <= 1'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        is_normal_end_fu_148 <= is_normal_end_1_fu_399_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        is_special_end_fu_144 <= 1'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        is_special_end_fu_144 <= is_special_end_1_fu_387_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lit_len_ge_15_fu_152 <= 1'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lit_len_ge_15_fu_152 <= lit_len_ge_15_1_fu_405_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lit_len_gt_0_fu_156 <= 1'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lit_len_gt_0_fu_156 <= lit_len_gt_0_1_fu_411_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            lit_length_fu_124 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0))) begin
            lit_length_fu_124 <= lit_length_4_fu_828_p3;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd1))) begin
            lit_length_fu_124 <= lit_length_6_fu_698_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        match_len_ge_15_fu_160 <= 1'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        match_len_ge_15_fu_160 <= match_len_ge_15_1_fu_417_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            match_length_fu_128 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0))) begin
            match_length_fu_128 <= match_length_14_fu_868_p3;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd2))) begin
            match_length_fu_128 <= match_length_16_fu_532_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        match_offset_plus_one_fu_176 <= 16'd0;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        match_offset_plus_one_fu_176 <= match_offset_plus_one_1_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_725)) begin
                        next_state_fu_136[0] <= 1'b0;
            next_state_fu_136[1] <= 1'b0;
            next_state_fu_136[2] <= 1'b0;
        end else if ((1'b1 == ap_condition_721)) begin
                        next_state_fu_136[2 : 0] <= zext_ln269_fu_858_p1[2 : 0];
        end else if ((1'b1 == ap_condition_743)) begin
                        next_state_fu_136[2 : 0] <= select_ln152_fu_706_p3[2 : 0];
        end else if ((1'b1 == ap_condition_740)) begin
                        next_state_fu_136[2 : 0] <= zext_ln151_fu_651_p1[2 : 0];
        end else if ((1'b1 == ap_condition_737)) begin
                        next_state_fu_136[0] <= 1'b1;
            next_state_fu_136[1] <= 1'b0;
            next_state_fu_136[2] <= 1'b1;
        end else if ((1'b1 == ap_condition_733)) begin
                        next_state_fu_136[2 : 0] <= select_ln330_fu_575_p3[2 : 0];
        end else if ((1'b1 == ap_condition_730)) begin
                        next_state_fu_136[2 : 0] <= select_ln153_fu_540_p3[2 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            readOffsetFlag_1_fu_116 <= 1'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0))) begin
            readOffsetFlag_1_fu_116 <= lit_ending_fu_767_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_725)) begin
            readOffsetFlag_fu_140 <= 1'd1;
        end else if ((1'b1 == ap_condition_749)) begin
            readOffsetFlag_fu_140 <= 1'd0;
        end else if ((1'b1 == ap_condition_746)) begin
            readOffsetFlag_fu_140 <= 1'd0;
        end else if ((1'b1 == ap_condition_740)) begin
            readOffsetFlag_fu_140 <= readOffsetFlag_6_fu_637_p2;
        end else if ((1'b1 == ap_condition_737)) begin
            readOffsetFlag_fu_140 <= 1'd0;
        end else if ((1'b1 == ap_condition_733)) begin
            readOffsetFlag_fu_140 <= readOffsetFlag_7_fu_583_p2;
        end else if ((1'b1 == ap_condition_730)) begin
            readOffsetFlag_fu_140 <= readOffsetFlag_8_fu_527_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_149)) begin
        if ((ap_loop_init == 1'b1)) begin
            write_lit_length_fu_132 <= 16'd0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0))) begin
            write_lit_length_fu_132 <= lit_length_7_fu_729_p1;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd3))) begin
            write_lit_length_fu_132 <= write_lit_length_2_fu_617_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compressedSize_1_reg_1077 <= compressedSize_fu_164;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inIdx_2_reg_1063 <= inIdx_fu_112;
        or_ln182_reg_1073 <= or_ln182_fu_340_p2;
        readOffsetFlag_3_reg_1068 <= readOffsetFlag_fu_140;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lit_len_tmp_fu_172 <= {{lenOffset_Stream_dout[63:32]}};
        match_len_tmp_fu_168 <= match_len_tmp_1_fu_363_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        next_state_load_reg_1086[2 : 0] <= next_state_fu_136[2 : 0];
        should_write_reg_1082 <= should_write_fu_350_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (or_ln182_reg_1073 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(next_state_load_reg_1086 == 32'd0) & ~(next_state_load_reg_1086 == 32'd1) & ~(next_state_load_reg_1086 == 32'd4) & ~(next_state_load_reg_1086 == 32'd5) & ~(next_state_load_reg_1086 == 32'd2) & ~(next_state_load_reg_1086 == 32'd3))) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = 8'd0;
    end else if ((next_state_load_reg_1086 == 32'd0)) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = outValue_fu_805_p3;
    end else if ((next_state_load_reg_1086 == 32'd1)) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = outValue_6_fu_683_p3;
    end else if ((next_state_load_reg_1086 == 32'd3)) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = lit_outStream_dout;
    end else if ((next_state_load_reg_1086 == 32'd4)) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = outValue_8_fu_599_p1;
    end else if ((next_state_load_reg_1086 == 32'd5)) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = {{match_offset_plus_one_fu_176[15:8]}};
    end else if ((next_state_load_reg_1086 == 32'd2)) begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = outValue_10_fu_506_p3;
    end else begin
        ap_phi_mux_outValue_11_phi_fu_223_p14 = ap_phi_reg_pp0_iter1_outValue_11_reg_220;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (or_ln182_reg_1073 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compressedSize_out_ap_vld = 1'b1;
    end else begin
        compressedSize_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_grp1) & (ap_predicate_op56_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lenOffset_Stream_blk_n = lenOffset_Stream_empty_n;
    end else begin
        lenOffset_Stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001_grp1) & (ap_predicate_op56_read_state3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        lenOffset_Stream_read = 1'b1;
    end else begin
        lenOffset_Stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (next_state_load_reg_1086 == 32'd3))) begin
        lit_outStream_blk_n = lit_outStream_empty_n;
    end else begin
        lit_outStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (next_state_load_reg_1086 == 32'd3))) begin
        lit_outStream_read = 1'b1;
    end else begin
        lit_outStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (should_write_reg_1082 == 1'd1))) begin
        lz4Out_blk_n = lz4Out_full_n;
    end else begin
        lz4Out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (should_write_reg_1082 == 1'd1))) begin
        lz4Out_eos_blk_n = lz4Out_eos_full_n;
    end else begin
        lz4Out_eos_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (should_write_reg_1082 == 1'd1))) begin
        lz4Out_eos_write = 1'b1;
    end else begin
        lz4Out_eos_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (should_write_reg_1082 == 1'd1))) begin
        lz4Out_write = 1'b1;
    end else begin
        lz4Out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln228_fu_733_p2 = (match_len_tmp_fu_168 + 16'd4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_01001_grp3 = ((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp3));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = ((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp3));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp3)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp2))));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp2 = ((1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = ((1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state4_pp0_stage0_iter1_grp3));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp1 = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b1 == ap_block_state3_pp0_stage2_iter0_grp1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp1 = ((ap_predicate_op56_read_state3 == 1'b1) & (lenOffset_Stream_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1_grp2 = (((lz4Out_full_n == 1'b0) & (should_write_reg_1082 == 1'd1)) | ((lit_outStream_empty_n == 1'b0) & (next_state_load_reg_1086 == 32'd3)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1_grp3 = ((lz4Out_eos_full_n == 1'b0) & (should_write_reg_1082 == 1'd1));
end

always @ (*) begin
    ap_condition_149 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_711 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_721 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0));
end

always @ (*) begin
    ap_condition_725 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_loop_init == 1'b1));
end

always @ (*) begin
    ap_condition_730 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd2));
end

always @ (*) begin
    ap_condition_733 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd5));
end

always @ (*) begin
    ap_condition_737 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd4));
end

always @ (*) begin
    ap_condition_740 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd3));
end

always @ (*) begin
    ap_condition_743 = ((1'b0 == ap_block_pp0_stage0_11001_grp2) & (1'b0 == ap_block_pp0_stage0_subdone_grp2_done_reg) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd1));
end

always @ (*) begin
    ap_condition_746 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd1));
end

always @ (*) begin
    ap_condition_749 = ((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (next_state_load_reg_1086 == 32'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter1_outValue_11_reg_220 = 'bx;

always @ (*) begin
    ap_predicate_op56_read_state3 = ((readOffsetFlag_3_reg_1068 == 1'd1) & (or_ln182_reg_1073 == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign compressedSize_2_fu_916_p2 = (compressedSize_1_reg_1077 + 32'd1);

assign compressedSize_out = compressedSize_fu_164;

assign icmp_ln182_fu_329_p2 = ((inIdx_fu_112 < input_size_4) ? 1'b1 : 1'b0);

assign icmp_ln201_1_fu_381_p2 = ((match_off_tmp_fu_367_p3 == 16'd777) ? 1'b1 : 1'b0);

assign icmp_ln201_fu_375_p2 = ((match_len_tmp_1_fu_363_p1 == 16'd777) ? 1'b1 : 1'b0);

assign icmp_ln310_fu_623_p2 = ((write_lit_length_2_fu_617_p2 == 16'd0) ? 1'b1 : 1'b0);

assign inIdx_3_fu_749_p2 = (inIdx_2_reg_1063 + zext_ln237_fu_745_p1);

assign inIdx_4_fu_754_p3 = ((is_special_end_fu_144[0:0] == 1'b1) ? input_size_4 : inIdx_3_fu_749_p2);

assign is_normal_end_1_fu_399_p2 = ((or_ln202_fu_393_p2 == 16'd0) ? 1'b1 : 1'b0);

assign is_special_end_1_fu_387_p2 = (icmp_ln201_fu_375_p2 & icmp_ln201_1_fu_381_p2);

assign lit_ending_fu_767_p2 = (or_ln246_fu_761_p2 | is_special_end_fu_144);

assign lit_len_ge_15_1_fu_405_p2 = ((lit_len_tmp_1_fu_355_p3 > 32'd14) ? 1'b1 : 1'b0);

assign lit_len_ge_255_fu_673_p2 = ((lit_length_fu_124 > 16'd254) ? 1'b1 : 1'b0);

assign lit_len_gt_0_1_fu_411_p2 = ((lit_len_tmp_1_fu_355_p3 != 32'd0) ? 1'b1 : 1'b0);

assign lit_len_tmp_1_fu_355_p3 = {{lenOffset_Stream_dout[63:32]}};

assign lit_length_2_fu_814_p2 = ($signed(lit_length_7_fu_729_p1) + $signed(16'd65521));

assign lit_length_3_fu_820_p3 = ((lit_len_gt_0_fu_156[0:0] == 1'b1) ? 16'd0 : lit_length_7_fu_729_p1);

assign lit_length_4_fu_828_p3 = ((lit_len_ge_15_fu_152[0:0] == 1'b1) ? lit_length_2_fu_814_p2 : lit_length_3_fu_820_p3);

assign lit_length_5_fu_692_p2 = ($signed(lit_length_fu_124) + $signed(16'd65281));

assign lit_length_6_fu_698_p3 = ((lit_len_ge_255_fu_673_p2[0:0] == 1'b1) ? lit_length_5_fu_692_p2 : lit_length_fu_124);

assign lit_length_7_fu_729_p1 = lit_len_tmp_fu_172[15:0];

assign lit_token_1_fu_785_p3 = ((lit_len_ge_15_fu_152[0:0] == 1'b1) ? 4'd15 : lit_token_fu_777_p3);

assign lit_token_fu_777_p3 = ((lit_len_gt_0_fu_156[0:0] == 1'b1) ? trunc_ln256_fu_773_p1 : 4'd0);

assign lz4Out_din = ap_phi_mux_outValue_11_phi_fu_223_p14;

assign lz4Out_eos_din = 1'd0;

assign match_len_ge_15_1_fu_417_p2 = ((match_len_tmp_1_fu_363_p1 > 16'd14) ? 1'b1 : 1'b0);

assign match_len_ge_255_fu_496_p2 = ((match_length_fu_128 > 16'd254) ? 1'b1 : 1'b0);

assign match_len_tmp_1_fu_363_p1 = lenOffset_Stream_dout[15:0];

assign match_length_13_fu_862_p2 = ($signed(match_len_tmp_fu_168) + $signed(16'd65521));

assign match_length_14_fu_868_p3 = ((match_len_ge_15_fu_160[0:0] == 1'b1) ? match_length_13_fu_862_p2 : 16'd0);

assign match_length_15_fu_515_p2 = ($signed(match_length_fu_128) + $signed(16'd65281));

assign match_length_16_fu_532_p3 = ((match_len_ge_255_fu_496_p2[0:0] == 1'b1) ? match_length_15_fu_515_p2 : match_length_fu_128);

assign match_off_tmp_fu_367_p3 = {{lenOffset_Stream_dout[31:16]}};

assign match_offset_plus_one_1_fu_423_p2 = (match_off_tmp_fu_367_p3 + 16'd1);

assign match_token_1_fu_797_p3 = ((match_len_ge_15_fu_160[0:0] == 1'b1) ? 4'd15 : match_token_fu_793_p1);

assign match_token_fu_793_p1 = match_len_tmp_fu_168[3:0];

assign next_state_2_fu_629_p3 = ((readOffsetFlag_1_fu_116[0:0] == 1'b1) ? 3'd0 : 3'd4);

assign next_state_3_fu_643_p3 = ((icmp_ln310_fu_623_p2[0:0] == 1'b1) ? next_state_2_fu_629_p3 : 3'd3);

assign next_state_tmp_fu_850_p3 = ((or_ln270_fu_844_p2[0:0] == 1'b1) ? select_ln270_1_fu_836_p3 : 3'd4);

assign or_ln182_fu_340_p2 = (xor_ln182_fu_334_p2 | icmp_ln182_fu_329_p2);

assign or_ln202_fu_393_p2 = (match_off_tmp_fu_367_p3 | match_len_tmp_1_fu_363_p1);

assign or_ln246_fu_761_p2 = (readOffsetFlag_1_fu_116 | is_normal_end_fu_148);

assign or_ln270_fu_844_p2 = (lit_len_gt_0_fu_156 | lit_len_ge_15_fu_152);

assign outValue_10_fu_506_p3 = ((match_len_ge_255_fu_496_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln336_fu_502_p1);

assign outValue_6_fu_683_p3 = ((lit_len_ge_255_fu_673_p2[0:0] == 1'b1) ? 8'd255 : trunc_ln295_fu_679_p1);

assign outValue_8_fu_599_p1 = match_offset_plus_one_fu_176[7:0];

assign outValue_fu_805_p3 = {{lit_token_1_fu_785_p3}, {match_token_1_fu_797_p3}};

assign readOffsetFlag_6_fu_637_p2 = (readOffsetFlag_1_fu_116 & icmp_ln310_fu_623_p2);

assign readOffsetFlag_7_fu_583_p2 = (extra_match_len_fu_120 ^ 1'd1);

assign readOffsetFlag_8_fu_527_p2 = (xor_ln338_fu_521_p2 | readOffsetFlag_3_reg_1068);

assign select_ln152_fu_706_p3 = ((lit_len_ge_255_fu_673_p2[0:0] == 1'b1) ? 32'd1 : 32'd3);

assign select_ln153_fu_540_p3 = ((match_len_ge_255_fu_496_p2[0:0] == 1'b1) ? 32'd2 : 32'd0);

assign select_ln270_1_fu_836_p3 = ((lit_len_ge_15_fu_152[0:0] == 1'b1) ? 3'd1 : 3'd3);

assign select_ln330_fu_575_p3 = ((extra_match_len_fu_120[0:0] == 1'b1) ? 32'd2 : 32'd0);

assign should_write_fu_350_p2 = ((compressedSize_fu_164 < input_size_4) ? 1'b1 : 1'b0);

assign sum_with_4_low_fu_739_p2 = (add_ln228_fu_733_p2 + lit_length_7_fu_729_p1);

assign trunc_ln256_fu_773_p1 = lit_len_tmp_fu_172[3:0];

assign trunc_ln295_fu_679_p1 = lit_length_fu_124[7:0];

assign trunc_ln336_fu_502_p1 = match_length_fu_128[7:0];

assign write_lit_length_2_fu_617_p2 = ($signed(write_lit_length_fu_132) + $signed(16'd65535));

assign xor_ln182_fu_334_p2 = (readOffsetFlag_fu_140 ^ 1'd1);

assign xor_ln338_fu_521_p2 = (match_len_ge_255_fu_496_p2 ^ 1'd1);

assign zext_ln151_fu_651_p1 = next_state_3_fu_643_p3;

assign zext_ln237_fu_745_p1 = sum_with_4_low_fu_739_p2;

assign zext_ln269_fu_858_p1 = next_state_tmp_fu_850_p3;

always @ (posedge ap_clk) begin
    next_state_load_reg_1086[31:3] <= 29'b00000000000000000000000000000;
    next_state_fu_136[31:3] <= 29'b00000000000000000000000000000;
end

endmodule //lz4CompressEngineRun_lz4CompressPart2_Pipeline_lz4_compress
