// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        inStream_dout,
        inStream_empty_n,
        inStream_read,
        compressdStream_din,
        compressdStream_full_n,
        compressdStream_write,
        compressdStream_num_data_valid,
        compressdStream_fifo_cap,
        arrayidx48_promoted187_reload,
        arrayidx42_3_promoted185_reload,
        arrayidx71_promoted183_reload,
        arrayidx61_promoted181_reload,
        arrayidx54_promoted179_reload,
        sub27,
        dict_3_address0,
        dict_3_ce0,
        dict_3_q0,
        dict_3_address1,
        dict_3_ce1,
        dict_3_we1,
        dict_3_d1,
        dict_2_address0,
        dict_2_ce0,
        dict_2_q0,
        dict_2_address1,
        dict_2_ce1,
        dict_2_we1,
        dict_2_d1,
        dict_1_address0,
        dict_1_ce0,
        dict_1_q0,
        dict_1_address1,
        dict_1_ce1,
        dict_1_we1,
        dict_1_d1,
        dict_address0,
        dict_ce0,
        dict_q0,
        dict_address1,
        dict_ce1,
        dict_we1,
        dict_d1,
        present_window_15_out,
        present_window_15_out_ap_vld,
        present_window_14_out,
        present_window_14_out_ap_vld,
        present_window_13_out,
        present_window_13_out_ap_vld,
        present_window_12_out,
        present_window_12_out_ap_vld,
        present_window_11_out,
        present_window_11_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] inStream_dout;
input   inStream_empty_n;
output   inStream_read;
output  [31:0] compressdStream_din;
input   compressdStream_full_n;
output   compressdStream_write;
input  [3:0] compressdStream_num_data_valid;
input  [3:0] compressdStream_fifo_cap;
input  [7:0] arrayidx48_promoted187_reload;
input  [7:0] arrayidx42_3_promoted185_reload;
input  [7:0] arrayidx71_promoted183_reload;
input  [7:0] arrayidx61_promoted181_reload;
input  [7:0] arrayidx54_promoted179_reload;
input  [31:0] sub27;
output  [7:0] dict_3_address0;
output   dict_3_ce0;
input  [407:0] dict_3_q0;
output  [7:0] dict_3_address1;
output   dict_3_ce1;
output   dict_3_we1;
output  [407:0] dict_3_d1;
output  [7:0] dict_2_address0;
output   dict_2_ce0;
input  [407:0] dict_2_q0;
output  [7:0] dict_2_address1;
output   dict_2_ce1;
output   dict_2_we1;
output  [407:0] dict_2_d1;
output  [7:0] dict_1_address0;
output   dict_1_ce0;
input  [407:0] dict_1_q0;
output  [7:0] dict_1_address1;
output   dict_1_ce1;
output   dict_1_we1;
output  [407:0] dict_1_d1;
output  [7:0] dict_address0;
output   dict_ce0;
input  [407:0] dict_q0;
output  [7:0] dict_address1;
output   dict_ce1;
output   dict_we1;
output  [407:0] dict_d1;
output  [7:0] present_window_15_out;
output   present_window_15_out_ap_vld;
output  [7:0] present_window_14_out;
output   present_window_14_out_ap_vld;
output  [7:0] present_window_13_out;
output   present_window_13_out_ap_vld;
output  [7:0] present_window_12_out;
output   present_window_12_out_ap_vld;
output  [7:0] present_window_11_out;
output   present_window_11_out_ap_vld;

reg ap_idle;
reg inStream_read;
reg compressdStream_write;
reg present_window_15_out_ap_vld;
reg present_window_14_out_ap_vld;
reg present_window_13_out_ap_vld;
reg present_window_12_out_ap_vld;
reg present_window_11_out_ap_vld;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg    ap_block_pp0_stage2_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln93_reg_2718;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    compressdStream_blk_n;
wire    ap_block_pp0_stage2_grp2;
reg    inStream_blk_n;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] i_1_reg_2656;
reg    ap_block_state5_pp0_stage1_iter1_grp1;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] i_1_reg_2656_pp0_iter1_reg;
reg   [7:0] present_window_11_load_reg_2662;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
reg   [7:0] present_window_11_load_reg_2662_pp0_iter1_reg;
reg   [7:0] present_window_11_load_reg_2662_pp0_iter2_reg;
reg   [7:0] present_window_11_load_reg_2662_pp0_iter3_reg;
reg   [7:0] present_window_12_load_reg_2676;
reg   [7:0] present_window_12_load_reg_2676_pp0_iter1_reg;
reg   [7:0] present_window_12_load_reg_2676_pp0_iter2_reg;
reg   [7:0] present_window_13_load_reg_2690;
reg   [7:0] present_window_13_load_reg_2690_pp0_iter1_reg;
reg   [7:0] present_window_13_load_reg_2690_pp0_iter2_reg;
reg   [7:0] present_window_14_load_reg_2704;
reg   [7:0] present_window_14_load_reg_2704_pp0_iter1_reg;
reg   [7:0] present_window_14_load_reg_2704_pp0_iter2_reg;
wire   [0:0] icmp_ln93_fu_519_p2;
reg   [0:0] icmp_ln93_reg_2718_pp0_iter1_reg;
reg   [0:0] icmp_ln93_reg_2718_pp0_iter2_reg;
wire   [9:0] add_ln123_4_fu_564_p2;
reg   [9:0] add_ln123_4_reg_2722;
wire   [1:0] trunc_ln111_fu_621_p1;
reg   [1:0] trunc_ln111_reg_2727;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
reg   [7:0] lshr_ln1_reg_2732;
reg   [7:0] present_window_15_load_reg_2737;
reg   [7:0] present_window_15_load_reg_2737_pp0_iter2_reg;
reg   [7:0] dict_addr_reg_2749;
reg   [7:0] dict_1_addr_reg_2755;
reg   [7:0] dict_2_addr_reg_2761;
reg   [7:0] dict_3_addr_reg_2767;
reg   [7:0] new_byte_reg_2773;
reg    ap_block_pp0_stage1_11001_grp1;
wire   [407:0] dictReadValue_reg_fu_672_p11;
reg   [407:0] dictReadValue_reg_reg_2784;
wire   [339:0] trunc_ln127_fu_695_p1;
reg   [339:0] trunc_ln127_reg_2830;
wire   [31:0] currIdx_reg_fu_704_p2;
reg   [31:0] currIdx_reg_reg_2835;
reg   [19:0] compareIdx_reg_2851;
wire   [1:0] len_2_fu_785_p3;
reg   [1:0] len_2_reg_2856;
wire   [0:0] done_2_fu_807_p2;
reg   [0:0] done_2_reg_2861;
wire   [1:0] len_3_fu_813_p2;
reg   [1:0] len_3_reg_2867;
wire   [0:0] icmp_ln168_2_fu_828_p2;
reg   [0:0] icmp_ln168_2_reg_2872;
wire   [0:0] icmp_ln168_3_fu_842_p2;
reg   [0:0] icmp_ln168_3_reg_2877;
wire   [0:0] icmp_ln168_4_fu_856_p2;
reg   [0:0] icmp_ln168_4_reg_2882;
reg   [19:0] compareIdx_1_reg_2887;
wire   [1:0] len_13_fu_922_p3;
reg   [1:0] len_13_reg_2892;
wire   [0:0] done_7_fu_944_p2;
reg   [0:0] done_7_reg_2897;
wire   [1:0] len_14_fu_950_p2;
reg   [1:0] len_14_reg_2903;
wire   [0:0] icmp_ln168_8_fu_965_p2;
reg   [0:0] icmp_ln168_8_reg_2908;
wire   [0:0] icmp_ln168_9_fu_979_p2;
reg   [0:0] icmp_ln168_9_reg_2913;
wire   [0:0] icmp_ln168_10_fu_993_p2;
reg   [0:0] icmp_ln168_10_reg_2918;
reg   [19:0] compareIdx_2_reg_2923;
wire   [0:0] len_22_fu_1016_p2;
reg   [0:0] len_22_reg_2928;
wire   [0:0] icmp_ln168_12_fu_1030_p2;
reg   [0:0] icmp_ln168_12_reg_2935;
wire   [0:0] icmp_ln168_13_fu_1044_p2;
reg   [0:0] icmp_ln168_13_reg_2940;
wire   [0:0] icmp_ln168_14_fu_1058_p2;
reg   [0:0] icmp_ln168_14_reg_2945;
wire   [0:0] icmp_ln168_15_fu_1072_p2;
reg   [0:0] icmp_ln168_15_reg_2950;
wire   [0:0] icmp_ln168_16_fu_1086_p2;
reg   [0:0] icmp_ln168_16_reg_2955;
reg    ap_block_pp0_stage2_11001_grp2;
reg   [19:0] compareIdx_3_reg_2960;
wire   [0:0] len_33_fu_1109_p2;
reg   [0:0] len_33_reg_2965;
wire   [0:0] icmp_ln168_18_fu_1123_p2;
reg   [0:0] icmp_ln168_18_reg_2972;
wire   [0:0] icmp_ln168_19_fu_1137_p2;
reg   [0:0] icmp_ln168_19_reg_2977;
wire   [0:0] icmp_ln168_20_fu_1151_p2;
reg   [0:0] icmp_ln168_20_reg_2982;
wire   [0:0] icmp_ln168_21_fu_1165_p2;
reg   [0:0] icmp_ln168_21_reg_2987;
wire   [0:0] icmp_ln168_22_fu_1179_p2;
reg   [0:0] icmp_ln168_22_reg_2992;
reg   [0:0] icmp_ln168_22_reg_2992_pp0_iter2_reg;
reg   [19:0] compareIdx_4_reg_2997;
wire   [0:0] len_44_fu_1202_p2;
reg   [0:0] len_44_reg_3002;
wire   [0:0] done_21_fu_1227_p2;
reg   [0:0] done_21_reg_3008;
wire   [0:0] icmp_ln168_25_fu_1242_p2;
reg   [0:0] icmp_ln168_25_reg_3014;
wire   [0:0] icmp_ln168_26_fu_1256_p2;
reg   [0:0] icmp_ln168_26_reg_3019;
wire   [0:0] icmp_ln168_27_fu_1270_p2;
reg   [0:0] icmp_ln168_27_reg_3024;
wire   [0:0] icmp_ln168_28_fu_1284_p2;
reg   [0:0] icmp_ln168_28_reg_3029;
reg   [19:0] compareIdx_5_reg_3034;
wire   [0:0] len_55_fu_1307_p2;
reg   [0:0] len_55_reg_3039;
wire   [0:0] icmp_ln168_30_fu_1321_p2;
reg   [0:0] icmp_ln168_30_reg_3046;
wire   [0:0] icmp_ln168_31_fu_1335_p2;
reg   [0:0] icmp_ln168_31_reg_3051;
wire   [0:0] icmp_ln168_32_fu_1349_p2;
reg   [0:0] icmp_ln168_32_reg_3056;
wire   [0:0] icmp_ln168_33_fu_1363_p2;
reg   [0:0] icmp_ln168_33_reg_3061;
reg   [0:0] icmp_ln168_33_reg_3061_pp0_iter2_reg;
wire   [0:0] icmp_ln168_34_fu_1377_p2;
reg   [0:0] icmp_ln168_34_reg_3066;
reg   [0:0] icmp_ln168_34_reg_3066_pp0_iter2_reg;
wire   [0:0] done_4_fu_1412_p2;
reg   [0:0] done_4_reg_3071;
wire   [2:0] len_8_fu_1423_p3;
reg   [2:0] len_8_reg_3076;
wire   [0:0] icmp_ln178_fu_1431_p2;
reg   [0:0] icmp_ln178_reg_3082;
wire   [0:0] icmp_ln179_fu_1451_p2;
reg   [0:0] icmp_ln179_reg_3087;
wire   [31:0] match_offset_fu_1457_p2;
reg   [31:0] match_offset_reg_3092;
wire   [0:0] done_9_fu_1493_p2;
reg   [0:0] done_9_reg_3099;
wire   [2:0] len_19_fu_1504_p3;
reg   [2:0] len_19_reg_3104;
wire   [0:0] icmp_ln178_1_fu_1512_p2;
reg   [0:0] icmp_ln178_1_reg_3110;
wire   [31:0] sub_ln179_1_fu_1517_p2;
reg   [31:0] sub_ln179_1_reg_3115;
wire   [0:0] icmp_ln179_1_fu_1532_p2;
reg   [0:0] icmp_ln179_1_reg_3120;
wire   [1:0] len_26_fu_1577_p3;
reg   [1:0] len_26_reg_3125;
wire   [0:0] done_13_fu_1585_p2;
reg   [0:0] done_13_reg_3130;
wire   [1:0] len_37_fu_1629_p3;
reg   [1:0] len_37_reg_3136;
wire   [0:0] done_18_fu_1637_p2;
reg   [0:0] done_18_reg_3141;
wire   [2:0] len_50_fu_1692_p3;
reg   [2:0] len_50_reg_3147;
wire   [0:0] done_24_fu_1700_p2;
reg   [0:0] done_24_reg_3153;
wire   [1:0] len_59_fu_1744_p3;
reg   [1:0] len_59_reg_3159;
wire   [0:0] done_28_fu_1752_p2;
reg   [0:0] done_28_reg_3164;
wire   [2:0] len_67_fu_1804_p3;
reg   [2:0] len_67_reg_3170;
wire   [31:0] match_offset_1_fu_1811_p2;
reg   [31:0] match_offset_1_reg_3177;
wire   [0:0] done_14_fu_1859_p2;
reg   [0:0] done_14_reg_3182;
wire   [2:0] len_30_fu_1869_p3;
reg   [2:0] len_30_reg_3187;
wire   [0:0] icmp_ln178_2_fu_1877_p2;
reg   [0:0] icmp_ln178_2_reg_3193;
wire   [0:0] icmp_ln179_2_fu_1897_p2;
reg   [0:0] icmp_ln179_2_reg_3198;
wire   [31:0] match_offset_2_fu_1903_p2;
reg   [31:0] match_offset_2_reg_3203;
wire   [2:0] len_39_fu_1918_p3;
reg   [2:0] len_39_reg_3210;
wire   [0:0] done_19_fu_1925_p2;
reg   [0:0] done_19_reg_3216;
wire   [2:0] len_70_fu_1950_p3;
reg   [2:0] len_70_reg_3222;
wire   [0:0] and_ln191_fu_1982_p2;
reg   [0:0] and_ln191_reg_3230;
wire   [2:0] match_length_1_fu_1988_p3;
reg   [2:0] match_length_1_reg_3235;
wire   [0:0] and_ln191_10_fu_2001_p2;
reg   [0:0] and_ln191_10_reg_3241;
wire   [2:0] len_68_fu_2023_p3;
reg   [2:0] len_68_reg_3246;
wire   [2:0] len_41_fu_2068_p3;
reg   [2:0] len_41_reg_3251;
wire   [2:0] len_42_fu_2074_p2;
reg   [2:0] len_42_reg_3256;
wire   [0:0] icmp_ln178_3_fu_2080_p2;
reg   [0:0] icmp_ln178_3_reg_3261;
wire   [0:0] icmp_ln179_3_fu_2100_p2;
reg   [0:0] icmp_ln179_3_reg_3266;
wire   [31:0] match_offset_3_fu_2106_p2;
reg   [31:0] match_offset_3_reg_3271;
wire   [0:0] icmp_ln178_4_fu_2115_p2;
reg   [0:0] icmp_ln178_4_reg_3278;
wire   [31:0] sub_ln179_4_fu_2120_p2;
reg   [31:0] sub_ln179_4_reg_3283;
wire   [0:0] icmp_ln179_4_fu_2135_p2;
reg   [0:0] icmp_ln179_4_reg_3288;
wire   [0:0] icmp_ln178_5_fu_2144_p2;
reg   [0:0] icmp_ln178_5_reg_3293;
wire   [31:0] sub_ln179_5_fu_2149_p2;
reg   [31:0] sub_ln179_5_reg_3298;
wire   [0:0] icmp_ln179_5_fu_2164_p2;
reg   [0:0] icmp_ln179_5_reg_3303;
wire   [2:0] match_length_3_fu_2190_p3;
reg   [2:0] match_length_3_reg_3308;
wire   [0:0] and_ln191_2_fu_2224_p2;
reg   [0:0] and_ln191_2_reg_3313;
wire   [15:0] select_ln191_4_fu_2249_p3;
reg   [15:0] select_ln191_4_reg_3319;
wire   [31:0] match_offset_4_fu_2297_p2;
reg   [31:0] match_offset_4_reg_3324;
wire   [0:0] done_29_fu_2341_p2;
reg   [0:0] done_29_reg_3329;
wire   [2:0] len_63_fu_2351_p3;
reg   [2:0] len_63_reg_3334;
wire   [31:0] match_offset_5_fu_2359_p2;
reg   [31:0] match_offset_5_reg_3340;
wire   [0:0] and_ln191_3_fu_2397_p2;
reg   [0:0] and_ln191_3_reg_3347;
wire   [2:0] match_length_7_fu_2403_p3;
reg   [2:0] match_length_7_reg_3352;
wire   [0:0] and_ln191_22_fu_2416_p2;
reg   [0:0] and_ln191_22_reg_3358;
wire   [15:0] select_ln191_2_fu_2428_p3;
reg   [15:0] select_ln191_2_reg_3363;
wire   [2:0] len_71_fu_2452_p3;
reg   [2:0] len_71_reg_3368;
wire   [0:0] and_ln191_4_fu_2504_p2;
reg   [0:0] and_ln191_4_reg_3373;
wire   [2:0] match_length_9_fu_2509_p3;
reg   [2:0] match_length_9_reg_3378;
wire   [0:0] and_ln191_5_fu_2543_p2;
reg   [0:0] and_ln191_5_reg_3383;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln111_fu_638_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] i_fu_298;
wire   [31:0] i_2_fu_645_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage1;
reg   [7:0] present_window_11_fu_302;
wire    ap_block_pp0_stage1_grp0;
reg   [7:0] present_window_12_fu_306;
reg   [7:0] present_window_13_fu_310;
reg   [7:0] present_window_14_fu_314;
reg   [7:0] present_window_15_fu_318;
reg    ap_block_pp0_stage2_01001_grp2;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_block_pp0_stage2_11001;
reg    ap_loop_exit_ready_pp0_iter2_reg;
wire    ap_block_pp0_stage2_01001_grp0;
reg    dict_ce0_local;
reg    dict_we1_local;
wire   [407:0] dictWriteValue_fu_713_p9;
wire    ap_block_pp0_stage2_grp0;
reg    dict_ce1_local;
reg    dict_1_ce0_local;
reg    dict_1_we1_local;
reg    dict_1_ce1_local;
reg    dict_2_ce0_local;
reg    dict_2_we1_local;
reg    dict_2_ce1_local;
reg    dict_3_ce0_local;
reg    dict_3_we1_local;
reg    dict_3_ce1_local;
wire   [8:0] factor_fu_536_p3;
wire   [8:0] zext_ln119_fu_528_p1;
wire   [8:0] present_window_14_cast_fu_532_p1;
wire   [8:0] add_ln123_fu_548_p2;
wire   [9:0] zext_ln123_1_fu_554_p1;
wire   [9:0] zext_ln118_fu_524_p1;
wire   [9:0] add_ln123_3_fu_558_p2;
wire   [9:0] zext_ln123_fu_544_p1;
wire   [5:0] trunc_ln118_fu_570_p1;
wire   [6:0] trunc_ln119_fu_581_p1;
wire   [7:0] tmp1_fu_592_p2;
wire   [9:0] shl_ln1_fu_584_p3;
wire   [9:0] shl_ln_fu_573_p3;
wire   [9:0] add_ln123_1_fu_604_p2;
wire   [9:0] tmp_fu_596_p3;
wire   [9:0] add_ln123_2_fu_610_p2;
wire   [9:0] add_ln123_5_fu_616_p2;
wire   [407:0] dictReadValue_reg_fu_672_p9;
wire   [19:0] trunc_ln132_fu_709_p1;
wire   [7:0] trunc_ln168_fu_739_p1;
wire   [0:0] len_fu_742_p2;
wire   [7:0] tmp_2_fu_757_p4;
wire   [0:0] icmp_ln168_fu_766_p2;
wire   [0:0] done_fu_751_p2;
wire   [0:0] done_1_fu_771_p2;
wire   [1:0] zext_ln168_fu_747_p1;
wire   [1:0] len_1_fu_777_p3;
wire   [7:0] tmp_3_fu_793_p4;
wire   [0:0] icmp_ln168_1_fu_802_p2;
wire   [7:0] tmp_4_fu_819_p4;
wire   [7:0] tmp_5_fu_833_p4;
wire   [7:0] tmp_6_fu_847_p4;
wire   [7:0] tmp_8_fu_870_p4;
wire   [0:0] len_11_fu_879_p2;
wire   [7:0] tmp_9_fu_894_p4;
wire   [0:0] icmp_ln168_6_fu_903_p2;
wire   [0:0] done_5_fu_888_p2;
wire   [0:0] done_6_fu_908_p2;
wire   [1:0] zext_ln168_1_fu_884_p1;
wire   [1:0] len_12_fu_914_p3;
wire   [7:0] tmp_s_fu_930_p4;
wire   [0:0] icmp_ln168_7_fu_939_p2;
wire   [7:0] tmp_7_fu_956_p4;
wire   [7:0] tmp_10_fu_970_p4;
wire   [7:0] tmp_11_fu_984_p4;
wire   [7:0] tmp_12_fu_1007_p4;
wire   [7:0] tmp_13_fu_1021_p4;
wire   [7:0] tmp_14_fu_1035_p4;
wire   [7:0] tmp_15_fu_1049_p4;
wire   [7:0] tmp_16_fu_1063_p4;
wire   [7:0] tmp_17_fu_1077_p4;
wire   [7:0] tmp_18_fu_1100_p4;
wire   [7:0] tmp_19_fu_1114_p4;
wire   [7:0] tmp_20_fu_1128_p4;
wire   [7:0] tmp_21_fu_1142_p4;
wire   [7:0] tmp_22_fu_1156_p4;
wire   [7:0] tmp_23_fu_1170_p4;
wire   [7:0] tmp_24_fu_1193_p4;
wire   [7:0] tmp_25_fu_1213_p4;
wire   [0:0] icmp_ln168_24_fu_1222_p2;
wire   [0:0] done_20_fu_1207_p2;
wire   [7:0] tmp_26_fu_1233_p4;
wire   [7:0] tmp_27_fu_1247_p4;
wire   [7:0] tmp_28_fu_1261_p4;
wire   [7:0] tmp_29_fu_1275_p4;
wire   [7:0] tmp_30_fu_1298_p4;
wire   [7:0] tmp_31_fu_1312_p4;
wire   [7:0] tmp_32_fu_1326_p4;
wire   [7:0] tmp_33_fu_1340_p4;
wire   [7:0] tmp_34_fu_1354_p4;
wire   [7:0] tmp_35_fu_1368_p4;
wire   [1:0] len_4_fu_1385_p3;
wire   [2:0] zext_ln165_fu_1390_p1;
wire   [0:0] done_3_fu_1394_p2;
wire   [2:0] len_5_fu_1398_p2;
wire   [2:0] len_6_fu_1404_p3;
wire   [2:0] len_7_fu_1417_p2;
wire   [31:0] zext_ln161_fu_1382_p1;
wire   [31:0] sub_ln179_fu_1436_p2;
wire   [15:0] tmp_1_fu_1441_p4;
wire   [1:0] len_15_fu_1466_p3;
wire   [2:0] zext_ln165_1_fu_1471_p1;
wire   [0:0] done_8_fu_1475_p2;
wire   [2:0] len_16_fu_1479_p2;
wire   [2:0] len_17_fu_1485_p3;
wire   [2:0] len_18_fu_1498_p2;
wire   [31:0] zext_ln161_1_fu_1463_p1;
wire   [15:0] tmp_37_fu_1522_p4;
wire   [0:0] done_10_fu_1541_p2;
wire   [0:0] done_11_fu_1546_p2;
wire   [1:0] zext_ln168_2_fu_1538_p1;
wire   [1:0] len_23_fu_1551_p3;
wire   [1:0] len_24_fu_1558_p3;
wire   [0:0] done_12_fu_1566_p2;
wire   [1:0] len_25_fu_1571_p2;
wire   [0:0] done_15_fu_1593_p2;
wire   [0:0] done_16_fu_1598_p2;
wire   [1:0] zext_ln168_3_fu_1590_p1;
wire   [1:0] len_34_fu_1603_p3;
wire   [1:0] len_35_fu_1610_p3;
wire   [0:0] done_17_fu_1618_p2;
wire   [1:0] len_36_fu_1623_p2;
wire   [1:0] zext_ln168_4_fu_1642_p1;
wire   [1:0] len_45_fu_1645_p3;
wire   [1:0] len_46_fu_1652_p3;
wire   [0:0] done_22_fu_1659_p2;
wire   [1:0] len_47_fu_1663_p2;
wire   [1:0] len_48_fu_1669_p3;
wire   [2:0] zext_ln165_4_fu_1677_p1;
wire   [0:0] done_23_fu_1681_p2;
wire   [2:0] len_49_fu_1686_p2;
wire   [0:0] done_25_fu_1708_p2;
wire   [0:0] done_26_fu_1713_p2;
wire   [1:0] zext_ln168_5_fu_1705_p1;
wire   [1:0] len_56_fu_1718_p3;
wire   [1:0] len_57_fu_1725_p3;
wire   [0:0] done_27_fu_1733_p2;
wire   [1:0] len_58_fu_1738_p2;
wire   [0:0] or_ln168_fu_1757_p2;
wire   [2:0] len_9_fu_1761_p2;
wire   [2:0] len_66_fu_1766_p3;
wire   [0:0] icmp_ln185_1_fu_1784_p2;
wire   [0:0] icmp_ln185_fu_1778_p2;
wire   [0:0] or_ln168_5_fu_1795_p2;
wire   [2:0] len_20_fu_1799_p2;
wire   [0:0] icmp_ln185_3_fu_1828_p2;
wire   [0:0] icmp_ln185_2_fu_1822_p2;
wire   [2:0] zext_ln165_2_fu_1843_p1;
wire   [2:0] len_27_fu_1846_p2;
wire   [2:0] len_28_fu_1852_p3;
wire   [2:0] len_29_fu_1863_p2;
wire   [31:0] zext_ln161_2_fu_1840_p1;
wire   [31:0] sub_ln179_2_fu_1882_p2;
wire   [15:0] tmp_39_fu_1887_p4;
wire   [2:0] zext_ln165_3_fu_1909_p1;
wire   [2:0] len_38_fu_1912_p2;
wire   [2:0] len_51_fu_1929_p2;
wire   [2:0] len_52_fu_1934_p3;
wire   [0:0] or_ln168_20_fu_1940_p2;
wire   [2:0] len_53_fu_1944_p2;
wire   [0:0] or_ln185_fu_1789_p2;
wire   [0:0] and_ln191_6_fu_1958_p2;
wire   [0:0] icmp_ln180_fu_1773_p2;
wire   [0:0] tmp_46_fu_1969_p3;
wire   [0:0] and_ln191_8_fu_1977_p2;
wire   [0:0] and_ln191_7_fu_1963_p2;
wire   [0:0] or_ln185_1_fu_1834_p2;
wire   [0:0] and_ln191_9_fu_1996_p2;
wire   [0:0] icmp_ln180_1_fu_1816_p2;
wire   [0:0] or_ln168_10_fu_2014_p2;
wire   [2:0] len_31_fu_2018_p2;
wire   [0:0] icmp_ln185_5_fu_2049_p2;
wire   [0:0] icmp_ln185_4_fu_2043_p2;
wire   [2:0] len_40_fu_2063_p2;
wire   [31:0] zext_ln161_3_fu_2060_p1;
wire   [31:0] sub_ln179_3_fu_2085_p2;
wire   [15:0] tmp_41_fu_2090_p4;
wire   [31:0] zext_ln161_4_fu_2112_p1;
wire   [15:0] tmp_43_fu_2125_p4;
wire   [31:0] zext_ln161_5_fu_2141_p1;
wire   [15:0] tmp_45_fu_2154_p4;
wire   [0:0] tmp_36_fu_2007_p3;
wire   [0:0] icmp_ln191_fu_2170_p2;
wire   [0:0] and_ln191_11_fu_2174_p2;
wire   [0:0] and_ln191_12_fu_2180_p2;
wire   [0:0] and_ln191_1_fu_2185_p2;
wire   [0:0] or_ln185_2_fu_2054_p2;
wire   [0:0] and_ln191_13_fu_2202_p2;
wire   [0:0] icmp_ln180_2_fu_2038_p2;
wire   [0:0] tmp_38_fu_2030_p3;
wire   [0:0] icmp_ln191_1_fu_2196_p2;
wire   [0:0] and_ln191_15_fu_2213_p2;
wire   [0:0] and_ln191_16_fu_2219_p2;
wire   [0:0] and_ln191_14_fu_2207_p2;
wire   [15:0] trunc_ln191_fu_2230_p1;
wire   [15:0] trunc_ln191_1_fu_2233_p1;
wire   [0:0] or_ln191_2_fu_2244_p2;
wire   [15:0] select_ln191_fu_2236_p3;
wire   [0:0] or_ln168_15_fu_2257_p2;
wire   [2:0] len_69_fu_2261_p3;
wire   [0:0] icmp_ln185_7_fu_2286_p2;
wire   [0:0] icmp_ln185_6_fu_2280_p2;
wire   [0:0] icmp_ln185_9_fu_2313_p2;
wire   [0:0] icmp_ln185_8_fu_2308_p2;
wire   [2:0] zext_ln165_5_fu_2325_p1;
wire   [2:0] len_60_fu_2328_p2;
wire   [2:0] len_61_fu_2334_p3;
wire   [2:0] len_62_fu_2345_p2;
wire   [2:0] match_length_5_fu_2364_p3;
wire   [0:0] or_ln185_3_fu_2291_p2;
wire   [0:0] and_ln191_17_fu_2375_p2;
wire   [0:0] icmp_ln180_3_fu_2275_p2;
wire   [0:0] tmp_40_fu_2267_p3;
wire   [0:0] icmp_ln191_2_fu_2369_p2;
wire   [0:0] and_ln191_19_fu_2386_p2;
wire   [0:0] and_ln191_20_fu_2392_p2;
wire   [0:0] and_ln191_18_fu_2380_p2;
wire   [0:0] or_ln185_4_fu_2319_p2;
wire   [0:0] and_ln191_21_fu_2411_p2;
wire   [0:0] icmp_ln180_4_fu_2302_p2;
wire   [15:0] trunc_ln191_4_fu_2422_p1;
wire   [15:0] trunc_ln191_5_fu_2425_p1;
wire   [0:0] or_ln168_25_fu_2443_p2;
wire   [2:0] len_64_fu_2447_p2;
wire   [0:0] icmp_ln185_11_fu_2478_p2;
wire   [0:0] icmp_ln185_10_fu_2472_p2;
wire   [0:0] tmp_42_fu_2436_p3;
wire   [0:0] icmp_ln191_3_fu_2489_p2;
wire   [0:0] and_ln191_23_fu_2493_p2;
wire   [0:0] and_ln191_24_fu_2499_p2;
wire   [0:0] or_ln185_5_fu_2483_p2;
wire   [0:0] and_ln191_25_fu_2521_p2;
wire   [0:0] icmp_ln180_5_fu_2467_p2;
wire   [0:0] tmp_44_fu_2459_p3;
wire   [0:0] icmp_ln191_4_fu_2515_p2;
wire   [0:0] and_ln191_27_fu_2532_p2;
wire   [0:0] and_ln191_28_fu_2538_p2;
wire   [0:0] and_ln191_26_fu_2526_p2;
wire   [15:0] trunc_ln191_2_fu_2557_p1;
wire   [15:0] trunc_ln191_3_fu_2560_p1;
wire   [0:0] or_ln191_fu_2549_p2;
wire   [15:0] select_ln191_1_fu_2563_p3;
wire   [0:0] or_ln191_1_fu_2553_p2;
wire   [0:0] or_ln191_3_fu_2577_p2;
wire   [15:0] select_ln191_3_fu_2570_p3;
wire   [2:0] match_length_11_fu_2590_p3;
wire   [15:0] select_ln191_5_fu_2583_p3;
wire   [7:0] zext_ln148_fu_2595_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to3;
reg    ap_done_pending_pp0;
reg    ap_block_pp0;
reg    ap_predicate_op74_load_state4;
reg    ap_enable_operation_74;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_predicate_op86_load_state5;
reg    ap_enable_operation_86;
reg    ap_enable_state5_pp0_iter1_stage1;
reg    ap_predicate_op102_store_state6;
reg    ap_enable_operation_102;
reg    ap_enable_state6_pp0_iter1_stage2;
reg    ap_predicate_op75_load_state4;
reg    ap_enable_operation_75;
reg    ap_predicate_op87_load_state5;
reg    ap_enable_operation_87;
reg    ap_predicate_op100_store_state6;
reg    ap_enable_operation_100;
reg    ap_predicate_op76_load_state4;
reg    ap_enable_operation_76;
reg    ap_predicate_op88_load_state5;
reg    ap_enable_operation_88;
reg    ap_predicate_op98_store_state6;
reg    ap_enable_operation_98;
reg    ap_predicate_op77_load_state4;
reg    ap_enable_operation_77;
reg    ap_predicate_op89_load_state5;
reg    ap_enable_operation_89;
reg    ap_predicate_op104_store_state6;
reg    ap_enable_operation_104;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] dictReadValue_reg_fu_672_p1;
wire   [1:0] dictReadValue_reg_fu_672_p3;
wire  signed [1:0] dictReadValue_reg_fu_672_p5;
wire  signed [1:0] dictReadValue_reg_fu_672_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 i_fu_298 = 32'd0;
#0 present_window_11_fu_302 = 8'd0;
#0 present_window_12_fu_306 = 8'd0;
#0 present_window_13_fu_310 = 8'd0;
#0 present_window_14_fu_314 = 8'd0;
#0 present_window_15_fu_318 = 8'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) lz4CompressEngineRun_sparsemux_9_2_408_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 408 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 408 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 408 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 408 ),
    .def_WIDTH( 408 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 408 ))
sparsemux_9_2_408_1_1_U18(
    .din0(dict_q0),
    .din1(dict_1_q0),
    .din2(dict_2_q0),
    .din3(dict_3_q0),
    .def(dictReadValue_reg_fu_672_p9),
    .sel(trunc_ln111_reg_2727),
    .dout(dictReadValue_reg_fu_672_p11)
);

lz4CompressEngineRun_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_298 <= 32'd5;
        end else if (((icmp_ln93_reg_2718 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_298 <= i_2_fu_645_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_11_fu_302 <= arrayidx54_promoted179_reload;
        end else if (((icmp_ln93_reg_2718 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_11_fu_302 <= present_window_12_load_reg_2676;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_12_fu_306 <= arrayidx61_promoted181_reload;
        end else if (((icmp_ln93_reg_2718 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_12_fu_306 <= present_window_13_load_reg_2690;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_13_fu_310 <= arrayidx71_promoted183_reload;
        end else if (((icmp_ln93_reg_2718 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_13_fu_310 <= present_window_14_load_reg_2704;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            present_window_14_fu_314 <= arrayidx42_3_promoted185_reload;
        end else if (((icmp_ln93_reg_2718 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            present_window_14_fu_314 <= present_window_15_fu_318;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        present_window_15_fu_318 <= arrayidx48_promoted187_reload;
    end else if (((icmp_ln93_reg_2718 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        present_window_15_fu_318 <= inStream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln123_4_reg_2722 <= add_ln123_4_fu_564_p2;
        and_ln191_10_reg_3241 <= and_ln191_10_fu_2001_p2;
        and_ln191_4_reg_3373 <= and_ln191_4_fu_2504_p2;
        and_ln191_5_reg_3383 <= and_ln191_5_fu_2543_p2;
        and_ln191_reg_3230 <= and_ln191_fu_1982_p2;
        dictReadValue_reg_reg_2784 <= dictReadValue_reg_fu_672_p11;
        done_14_reg_3182 <= done_14_fu_1859_p2;
        done_19_reg_3216 <= done_19_fu_1925_p2;
        icmp_ln178_2_reg_3193 <= icmp_ln178_2_fu_1877_p2;
        icmp_ln179_2_reg_3198 <= icmp_ln179_2_fu_1897_p2;
        len_30_reg_3187 <= len_30_fu_1869_p3;
        len_39_reg_3210 <= len_39_fu_1918_p3;
        len_67_reg_3170 <= len_67_fu_1804_p3;
        len_70_reg_3222 <= len_70_fu_1950_p3;
        len_71_reg_3368 <= len_71_fu_2452_p3;
        match_length_1_reg_3235 <= match_length_1_fu_1988_p3;
        match_length_9_reg_3378 <= match_length_9_fu_2509_p3;
        match_offset_1_reg_3177 <= match_offset_1_fu_1811_p2;
        match_offset_2_reg_3203 <= match_offset_2_fu_1903_p2;
        present_window_11_load_reg_2662_pp0_iter1_reg <= present_window_11_load_reg_2662;
        present_window_11_load_reg_2662_pp0_iter2_reg <= present_window_11_load_reg_2662_pp0_iter1_reg;
        present_window_11_load_reg_2662_pp0_iter3_reg <= present_window_11_load_reg_2662_pp0_iter2_reg;
        present_window_12_load_reg_2676_pp0_iter1_reg <= present_window_12_load_reg_2676;
        present_window_12_load_reg_2676_pp0_iter2_reg <= present_window_12_load_reg_2676_pp0_iter1_reg;
        present_window_13_load_reg_2690_pp0_iter1_reg <= present_window_13_load_reg_2690;
        present_window_13_load_reg_2690_pp0_iter2_reg <= present_window_13_load_reg_2690_pp0_iter1_reg;
        present_window_14_load_reg_2704_pp0_iter1_reg <= present_window_14_load_reg_2704;
        present_window_14_load_reg_2704_pp0_iter2_reg <= present_window_14_load_reg_2704_pp0_iter1_reg;
        trunc_ln127_reg_2830 <= trunc_ln127_fu_695_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln191_22_reg_3358 <= and_ln191_22_fu_2416_p2;
        and_ln191_3_reg_3347 <= and_ln191_3_fu_2397_p2;
        dict_1_addr_reg_2755 <= zext_ln111_fu_638_p1;
        dict_2_addr_reg_2761 <= zext_ln111_fu_638_p1;
        dict_3_addr_reg_2767 <= zext_ln111_fu_638_p1;
        dict_addr_reg_2749 <= zext_ln111_fu_638_p1;
        done_13_reg_3130 <= done_13_fu_1585_p2;
        done_18_reg_3141 <= done_18_fu_1637_p2;
        done_24_reg_3153 <= done_24_fu_1700_p2;
        done_28_reg_3164 <= done_28_fu_1752_p2;
        done_29_reg_3329 <= done_29_fu_2341_p2;
        done_4_reg_3071 <= done_4_fu_1412_p2;
        done_9_reg_3099 <= done_9_fu_1493_p2;
        icmp_ln178_1_reg_3110 <= icmp_ln178_1_fu_1512_p2;
        icmp_ln178_reg_3082 <= icmp_ln178_fu_1431_p2;
        icmp_ln179_1_reg_3120 <= icmp_ln179_1_fu_1532_p2;
        icmp_ln179_reg_3087 <= icmp_ln179_fu_1451_p2;
        len_19_reg_3104 <= len_19_fu_1504_p3;
        len_26_reg_3125 <= len_26_fu_1577_p3;
        len_37_reg_3136 <= len_37_fu_1629_p3;
        len_50_reg_3147 <= len_50_fu_1692_p3;
        len_59_reg_3159 <= len_59_fu_1744_p3;
        len_63_reg_3334 <= len_63_fu_2351_p3;
        len_8_reg_3076 <= len_8_fu_1423_p3;
        match_length_7_reg_3352 <= match_length_7_fu_2403_p3;
        match_offset_4_reg_3324 <= match_offset_4_fu_2297_p2;
        match_offset_5_reg_3340 <= match_offset_5_fu_2359_p2;
        match_offset_reg_3092 <= match_offset_fu_1457_p2;
        present_window_15_load_reg_2737_pp0_iter2_reg <= present_window_15_load_reg_2737;
        select_ln191_2_reg_3363 <= select_ln191_2_fu_2428_p3;
        sub_ln179_1_reg_3115 <= sub_ln179_1_fu_1517_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        and_ln191_2_reg_3313 <= and_ln191_2_fu_2224_p2;
        icmp_ln168_16_reg_2955 <= icmp_ln168_16_fu_1086_p2;
        len_68_reg_3246 <= len_68_fu_2023_p3;
        match_length_3_reg_3308 <= match_length_3_fu_2190_p3;
        select_ln191_4_reg_3319 <= select_ln191_4_fu_2249_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compareIdx_1_reg_2887 <= {{dictReadValue_reg_reg_2784[135:116]}};
        compareIdx_2_reg_2923 <= {{dictReadValue_reg_reg_2784[203:184]}};
        compareIdx_3_reg_2960 <= {{dictReadValue_reg_reg_2784[271:252]}};
        compareIdx_4_reg_2997 <= {{dictReadValue_reg_reg_2784[339:320]}};
        compareIdx_5_reg_3034 <= {{dictReadValue_reg_reg_2784[407:388]}};
        compareIdx_reg_2851 <= {{dictReadValue_reg_reg_2784[67:48]}};
        currIdx_reg_reg_2835 <= currIdx_reg_fu_704_p2;
        done_21_reg_3008 <= done_21_fu_1227_p2;
        done_2_reg_2861 <= done_2_fu_807_p2;
        done_7_reg_2897 <= done_7_fu_944_p2;
        icmp_ln168_10_reg_2918 <= icmp_ln168_10_fu_993_p2;
        icmp_ln168_12_reg_2935 <= icmp_ln168_12_fu_1030_p2;
        icmp_ln168_13_reg_2940 <= icmp_ln168_13_fu_1044_p2;
        icmp_ln168_14_reg_2945 <= icmp_ln168_14_fu_1058_p2;
        icmp_ln168_15_reg_2950 <= icmp_ln168_15_fu_1072_p2;
        icmp_ln168_18_reg_2972 <= icmp_ln168_18_fu_1123_p2;
        icmp_ln168_19_reg_2977 <= icmp_ln168_19_fu_1137_p2;
        icmp_ln168_20_reg_2982 <= icmp_ln168_20_fu_1151_p2;
        icmp_ln168_21_reg_2987 <= icmp_ln168_21_fu_1165_p2;
        icmp_ln168_22_reg_2992 <= icmp_ln168_22_fu_1179_p2;
        icmp_ln168_22_reg_2992_pp0_iter2_reg <= icmp_ln168_22_reg_2992;
        icmp_ln168_25_reg_3014 <= icmp_ln168_25_fu_1242_p2;
        icmp_ln168_26_reg_3019 <= icmp_ln168_26_fu_1256_p2;
        icmp_ln168_27_reg_3024 <= icmp_ln168_27_fu_1270_p2;
        icmp_ln168_28_reg_3029 <= icmp_ln168_28_fu_1284_p2;
        icmp_ln168_2_reg_2872 <= icmp_ln168_2_fu_828_p2;
        icmp_ln168_30_reg_3046 <= icmp_ln168_30_fu_1321_p2;
        icmp_ln168_31_reg_3051 <= icmp_ln168_31_fu_1335_p2;
        icmp_ln168_32_reg_3056 <= icmp_ln168_32_fu_1349_p2;
        icmp_ln168_33_reg_3061 <= icmp_ln168_33_fu_1363_p2;
        icmp_ln168_33_reg_3061_pp0_iter2_reg <= icmp_ln168_33_reg_3061;
        icmp_ln168_34_reg_3066 <= icmp_ln168_34_fu_1377_p2;
        icmp_ln168_34_reg_3066_pp0_iter2_reg <= icmp_ln168_34_reg_3066;
        icmp_ln168_3_reg_2877 <= icmp_ln168_3_fu_842_p2;
        icmp_ln168_4_reg_2882 <= icmp_ln168_4_fu_856_p2;
        icmp_ln168_8_reg_2908 <= icmp_ln168_8_fu_965_p2;
        icmp_ln168_9_reg_2913 <= icmp_ln168_9_fu_979_p2;
        icmp_ln178_3_reg_3261 <= icmp_ln178_3_fu_2080_p2;
        icmp_ln178_4_reg_3278 <= icmp_ln178_4_fu_2115_p2;
        icmp_ln178_5_reg_3293 <= icmp_ln178_5_fu_2144_p2;
        icmp_ln179_3_reg_3266 <= icmp_ln179_3_fu_2100_p2;
        icmp_ln179_4_reg_3288 <= icmp_ln179_4_fu_2135_p2;
        icmp_ln179_5_reg_3303 <= icmp_ln179_5_fu_2164_p2;
        len_13_reg_2892 <= len_13_fu_922_p3;
        len_14_reg_2903 <= len_14_fu_950_p2;
        len_22_reg_2928 <= len_22_fu_1016_p2;
        len_2_reg_2856 <= len_2_fu_785_p3;
        len_33_reg_2965 <= len_33_fu_1109_p2;
        len_3_reg_2867 <= len_3_fu_813_p2;
        len_41_reg_3251 <= len_41_fu_2068_p3;
        len_42_reg_3256 <= len_42_fu_2074_p2;
        len_44_reg_3002 <= len_44_fu_1202_p2;
        len_55_reg_3039 <= len_55_fu_1307_p2;
        lshr_ln1_reg_2732 <= {{add_ln123_5_fu_616_p2[9:2]}};
        match_offset_3_reg_3271 <= match_offset_3_fu_2106_p2;
        sub_ln179_4_reg_3283 <= sub_ln179_4_fu_2120_p2;
        sub_ln179_5_reg_3298 <= sub_ln179_5_fu_2149_p2;
        trunc_ln111_reg_2727 <= trunc_ln111_fu_621_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_1_reg_2656 <= i_fu_298;
        i_1_reg_2656_pp0_iter1_reg <= i_1_reg_2656;
        icmp_ln93_reg_2718 <= icmp_ln93_fu_519_p2;
        icmp_ln93_reg_2718_pp0_iter1_reg <= icmp_ln93_reg_2718;
        icmp_ln93_reg_2718_pp0_iter2_reg <= icmp_ln93_reg_2718_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        new_byte_reg_2773 <= inStream_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        present_window_11_load_reg_2662 <= present_window_11_fu_302;
        present_window_12_load_reg_2676 <= present_window_12_fu_306;
        present_window_13_load_reg_2690 <= present_window_13_fu_310;
        present_window_14_load_reg_2704 <= present_window_14_fu_314;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        present_window_15_load_reg_2737 <= present_window_15_fu_318;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2718 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2718 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (~((ap_loop_exit_ready == 1'b0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_done_pending_pp0 = 1'b1;
    end else begin
        ap_done_pending_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to3 = 1'b1;
    end else begin
        ap_idle_pp0_1to3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_grp2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compressdStream_blk_n = compressdStream_full_n;
    end else begin
        compressdStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        compressdStream_write = 1'b1;
    end else begin
        compressdStream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dict_1_ce0_local = 1'b1;
    end else begin
        dict_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_1_ce1_local = 1'b1;
    end else begin
        dict_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2727 == 2'd1) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_1_we1_local = 1'b1;
    end else begin
        dict_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dict_2_ce0_local = 1'b1;
    end else begin
        dict_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_2_ce1_local = 1'b1;
    end else begin
        dict_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2727 == 2'd2) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_2_we1_local = 1'b1;
    end else begin
        dict_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dict_3_ce0_local = 1'b1;
    end else begin
        dict_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_3_ce1_local = 1'b1;
    end else begin
        dict_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2727 == 2'd3) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_3_we1_local = 1'b1;
    end else begin
        dict_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dict_ce0_local = 1'b1;
    end else begin
        dict_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_ce1_local = 1'b1;
    end else begin
        dict_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln111_reg_2727 == 2'd0) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        dict_we1_local = 1'b1;
    end else begin
        dict_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2718 == 1'd1) & (1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inStream_blk_n = inStream_empty_n;
    end else begin
        inStream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln93_reg_2718 == 1'd1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        inStream_read = 1'b1;
    end else begin
        inStream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2718_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_11_out_ap_vld = 1'b1;
    end else begin
        present_window_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2718_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_12_out_ap_vld = 1'b1;
    end else begin
        present_window_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2718_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_13_out_ap_vld = 1'b1;
    end else begin
        present_window_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2718_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_14_out_ap_vld = 1'b1;
    end else begin
        present_window_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (icmp_ln93_reg_2718_pp0_iter2_reg == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        present_window_15_out_ap_vld = 1'b1;
    end else begin
        present_window_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_done_pending_pp0 == 1'b0) & (ap_idle_pp0_1to3 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln123_1_fu_604_p2 = (shl_ln1_fu_584_p3 + shl_ln_fu_573_p3);

assign add_ln123_2_fu_610_p2 = (add_ln123_1_fu_604_p2 + tmp_fu_596_p3);

assign add_ln123_3_fu_558_p2 = (zext_ln123_1_fu_554_p1 + zext_ln118_fu_524_p1);

assign add_ln123_4_fu_564_p2 = (add_ln123_3_fu_558_p2 + zext_ln123_fu_544_p1);

assign add_ln123_5_fu_616_p2 = (add_ln123_4_reg_2722 + add_ln123_2_fu_610_p2);

assign add_ln123_fu_548_p2 = (zext_ln119_fu_528_p1 + present_window_14_cast_fu_532_p1);

assign and_ln191_10_fu_2001_p2 = (icmp_ln180_1_fu_1816_p2 & and_ln191_9_fu_1996_p2);

assign and_ln191_11_fu_2174_p2 = (tmp_36_fu_2007_p3 & icmp_ln191_fu_2170_p2);

assign and_ln191_12_fu_2180_p2 = (icmp_ln178_1_reg_3110 & and_ln191_11_fu_2174_p2);

assign and_ln191_13_fu_2202_p2 = (or_ln185_2_fu_2054_p2 & icmp_ln179_2_reg_3198);

assign and_ln191_14_fu_2207_p2 = (icmp_ln180_2_fu_2038_p2 & and_ln191_13_fu_2202_p2);

assign and_ln191_15_fu_2213_p2 = (tmp_38_fu_2030_p3 & icmp_ln191_1_fu_2196_p2);

assign and_ln191_16_fu_2219_p2 = (icmp_ln178_2_reg_3193 & and_ln191_15_fu_2213_p2);

assign and_ln191_17_fu_2375_p2 = (or_ln185_3_fu_2291_p2 & icmp_ln179_3_reg_3266);

assign and_ln191_18_fu_2380_p2 = (icmp_ln180_3_fu_2275_p2 & and_ln191_17_fu_2375_p2);

assign and_ln191_19_fu_2386_p2 = (tmp_40_fu_2267_p3 & icmp_ln191_2_fu_2369_p2);

assign and_ln191_1_fu_2185_p2 = (and_ln191_12_fu_2180_p2 & and_ln191_10_reg_3241);

assign and_ln191_20_fu_2392_p2 = (icmp_ln178_3_reg_3261 & and_ln191_19_fu_2386_p2);

assign and_ln191_21_fu_2411_p2 = (or_ln185_4_fu_2319_p2 & icmp_ln179_4_reg_3288);

assign and_ln191_22_fu_2416_p2 = (icmp_ln180_4_fu_2302_p2 & and_ln191_21_fu_2411_p2);

assign and_ln191_23_fu_2493_p2 = (tmp_42_fu_2436_p3 & icmp_ln191_3_fu_2489_p2);

assign and_ln191_24_fu_2499_p2 = (icmp_ln178_4_reg_3278 & and_ln191_23_fu_2493_p2);

assign and_ln191_25_fu_2521_p2 = (or_ln185_5_fu_2483_p2 & icmp_ln179_5_reg_3303);

assign and_ln191_26_fu_2526_p2 = (icmp_ln180_5_fu_2467_p2 & and_ln191_25_fu_2521_p2);

assign and_ln191_27_fu_2532_p2 = (tmp_44_fu_2459_p3 & icmp_ln191_4_fu_2515_p2);

assign and_ln191_28_fu_2538_p2 = (icmp_ln178_5_reg_3293 & and_ln191_27_fu_2532_p2);

assign and_ln191_2_fu_2224_p2 = (and_ln191_16_fu_2219_p2 & and_ln191_14_fu_2207_p2);

assign and_ln191_3_fu_2397_p2 = (and_ln191_20_fu_2392_p2 & and_ln191_18_fu_2380_p2);

assign and_ln191_4_fu_2504_p2 = (and_ln191_24_fu_2499_p2 & and_ln191_22_reg_3358);

assign and_ln191_5_fu_2543_p2 = (and_ln191_28_fu_2538_p2 & and_ln191_26_fu_2526_p2);

assign and_ln191_6_fu_1958_p2 = (or_ln185_fu_1789_p2 & icmp_ln179_reg_3087);

assign and_ln191_7_fu_1963_p2 = (icmp_ln180_fu_1773_p2 & and_ln191_6_fu_1958_p2);

assign and_ln191_8_fu_1977_p2 = (tmp_46_fu_1969_p3 & icmp_ln178_reg_3082);

assign and_ln191_9_fu_1996_p2 = (or_ln185_1_fu_1834_p2 & icmp_ln179_1_reg_3120);

assign and_ln191_fu_1982_p2 = (and_ln191_8_fu_1977_p2 & and_ln191_7_fu_1963_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage2 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage2_subdone)) | ((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state5_pp0_stage1_iter1_grp1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_01001_grp2 = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((compressdStream_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage1_iter1_grp1 = ((icmp_ln93_reg_2718 == 1'd1) & (inStream_empty_n == 1'b0));
end

assign ap_done = ap_done_sig;

always @ (*) begin
    ap_enable_operation_100 = (ap_predicate_op100_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_102 = (ap_predicate_op102_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_104 = (ap_predicate_op104_store_state6 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_74 = (ap_predicate_op74_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_75 = (ap_predicate_op75_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_76 = (ap_predicate_op76_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_77 = (ap_predicate_op77_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_86 = (ap_predicate_op86_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_87 = (ap_predicate_op87_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_88 = (ap_predicate_op88_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_89 = (ap_predicate_op89_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_98 = (ap_predicate_op98_store_state6 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter1_stage1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state6_pp0_iter1_stage2 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

always @ (*) begin
    ap_predicate_op100_store_state6 = ((trunc_ln111_reg_2727 == 2'd1) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op102_store_state6 = ((trunc_ln111_reg_2727 == 2'd0) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op104_store_state6 = ((trunc_ln111_reg_2727 == 2'd3) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op74_load_state4 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd0));
end

always @ (*) begin
    ap_predicate_op75_load_state4 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd1));
end

always @ (*) begin
    ap_predicate_op76_load_state4 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd2));
end

always @ (*) begin
    ap_predicate_op77_load_state4 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd3));
end

always @ (*) begin
    ap_predicate_op86_load_state5 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd0));
end

always @ (*) begin
    ap_predicate_op87_load_state5 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd1));
end

always @ (*) begin
    ap_predicate_op88_load_state5 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd2));
end

always @ (*) begin
    ap_predicate_op89_load_state5 = ((icmp_ln93_reg_2718 == 1'd1) & (trunc_ln111_reg_2727 == 2'd3));
end

always @ (*) begin
    ap_predicate_op98_store_state6 = ((trunc_ln111_reg_2727 == 2'd2) & (icmp_ln93_reg_2718_pp0_iter1_reg == 1'd1));
end

assign ap_ready = ap_ready_sig;

assign compressdStream_din = {{{select_ln191_5_fu_2583_p3}, {zext_ln148_fu_2595_p1}}, {present_window_11_load_reg_2662_pp0_iter3_reg}};

assign currIdx_reg_fu_704_p2 = ($signed(i_1_reg_2656_pp0_iter1_reg) + $signed(32'd4294967291));

assign dictReadValue_reg_fu_672_p9 = 'bx;

assign dictWriteValue_fu_713_p9 = {{{{{{{{trunc_ln127_reg_2830}, {trunc_ln132_fu_709_p1}}, {new_byte_reg_2773}}, {present_window_15_load_reg_2737}}, {present_window_14_load_reg_2704_pp0_iter1_reg}}, {present_window_13_load_reg_2690_pp0_iter1_reg}}, {present_window_12_load_reg_2676_pp0_iter1_reg}}, {present_window_11_load_reg_2662_pp0_iter1_reg}};

assign dict_1_address0 = zext_ln111_fu_638_p1;

assign dict_1_address1 = dict_1_addr_reg_2755;

assign dict_1_ce0 = dict_1_ce0_local;

assign dict_1_ce1 = dict_1_ce1_local;

assign dict_1_d1 = dictWriteValue_fu_713_p9;

assign dict_1_we1 = dict_1_we1_local;

assign dict_2_address0 = zext_ln111_fu_638_p1;

assign dict_2_address1 = dict_2_addr_reg_2761;

assign dict_2_ce0 = dict_2_ce0_local;

assign dict_2_ce1 = dict_2_ce1_local;

assign dict_2_d1 = dictWriteValue_fu_713_p9;

assign dict_2_we1 = dict_2_we1_local;

assign dict_3_address0 = zext_ln111_fu_638_p1;

assign dict_3_address1 = dict_3_addr_reg_2767;

assign dict_3_ce0 = dict_3_ce0_local;

assign dict_3_ce1 = dict_3_ce1_local;

assign dict_3_d1 = dictWriteValue_fu_713_p9;

assign dict_3_we1 = dict_3_we1_local;

assign dict_address0 = zext_ln111_fu_638_p1;

assign dict_address1 = dict_addr_reg_2749;

assign dict_ce0 = dict_ce0_local;

assign dict_ce1 = dict_ce1_local;

assign dict_d1 = dictWriteValue_fu_713_p9;

assign dict_we1 = dict_we1_local;

assign done_10_fu_1541_p2 = (len_22_reg_2928 ^ 1'd1);

assign done_11_fu_1546_p2 = (icmp_ln168_12_reg_2935 | done_10_fu_1541_p2);

assign done_12_fu_1566_p2 = (icmp_ln168_13_reg_2940 | done_11_fu_1546_p2);

assign done_13_fu_1585_p2 = (icmp_ln168_14_reg_2945 | done_12_fu_1566_p2);

assign done_14_fu_1859_p2 = (icmp_ln168_15_reg_2950 | done_13_reg_3130);

assign done_15_fu_1593_p2 = (len_33_reg_2965 ^ 1'd1);

assign done_16_fu_1598_p2 = (icmp_ln168_18_reg_2972 | done_15_fu_1593_p2);

assign done_17_fu_1618_p2 = (icmp_ln168_19_reg_2977 | done_16_fu_1598_p2);

assign done_18_fu_1637_p2 = (icmp_ln168_20_reg_2982 | done_17_fu_1618_p2);

assign done_19_fu_1925_p2 = (icmp_ln168_21_reg_2987 | done_18_reg_3141);

assign done_1_fu_771_p2 = (icmp_ln168_fu_766_p2 | done_fu_751_p2);

assign done_20_fu_1207_p2 = (len_44_fu_1202_p2 ^ 1'd1);

assign done_21_fu_1227_p2 = (icmp_ln168_24_fu_1222_p2 | done_20_fu_1207_p2);

assign done_22_fu_1659_p2 = (icmp_ln168_25_reg_3014 | done_21_reg_3008);

assign done_23_fu_1681_p2 = (icmp_ln168_26_reg_3019 | done_22_fu_1659_p2);

assign done_24_fu_1700_p2 = (icmp_ln168_27_reg_3024 | done_23_fu_1681_p2);

assign done_25_fu_1708_p2 = (len_55_reg_3039 ^ 1'd1);

assign done_26_fu_1713_p2 = (icmp_ln168_30_reg_3046 | done_25_fu_1708_p2);

assign done_27_fu_1733_p2 = (icmp_ln168_31_reg_3051 | done_26_fu_1713_p2);

assign done_28_fu_1752_p2 = (icmp_ln168_32_reg_3056 | done_27_fu_1733_p2);

assign done_29_fu_2341_p2 = (icmp_ln168_33_reg_3061_pp0_iter2_reg | done_28_reg_3164);

assign done_2_fu_807_p2 = (icmp_ln168_1_fu_802_p2 | done_1_fu_771_p2);

assign done_3_fu_1394_p2 = (icmp_ln168_2_reg_2872 | done_2_reg_2861);

assign done_4_fu_1412_p2 = (icmp_ln168_3_reg_2877 | done_3_fu_1394_p2);

assign done_5_fu_888_p2 = (len_11_fu_879_p2 ^ 1'd1);

assign done_6_fu_908_p2 = (icmp_ln168_6_fu_903_p2 | done_5_fu_888_p2);

assign done_7_fu_944_p2 = (icmp_ln168_7_fu_939_p2 | done_6_fu_908_p2);

assign done_8_fu_1475_p2 = (icmp_ln168_8_reg_2908 | done_7_reg_2897);

assign done_9_fu_1493_p2 = (icmp_ln168_9_reg_2913 | done_8_fu_1475_p2);

assign done_fu_751_p2 = (len_fu_742_p2 ^ 1'd1);

assign factor_fu_536_p3 = {{present_window_13_fu_310}, {1'd0}};

assign i_2_fu_645_p2 = (i_1_reg_2656 + 32'd1);

assign icmp_ln168_10_fu_993_p2 = ((tmp_11_fu_984_p4 != new_byte_reg_2773) ? 1'b1 : 1'b0);

assign icmp_ln168_12_fu_1030_p2 = ((tmp_13_fu_1021_p4 != present_window_12_load_reg_2676_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_13_fu_1044_p2 = ((tmp_14_fu_1035_p4 != present_window_13_load_reg_2690_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_14_fu_1058_p2 = ((tmp_15_fu_1049_p4 != present_window_14_load_reg_2704_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_15_fu_1072_p2 = ((tmp_16_fu_1063_p4 != present_window_15_load_reg_2737) ? 1'b1 : 1'b0);

assign icmp_ln168_16_fu_1086_p2 = ((tmp_17_fu_1077_p4 != new_byte_reg_2773) ? 1'b1 : 1'b0);

assign icmp_ln168_18_fu_1123_p2 = ((tmp_19_fu_1114_p4 != present_window_12_load_reg_2676_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_19_fu_1137_p2 = ((tmp_20_fu_1128_p4 != present_window_13_load_reg_2690_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_1_fu_802_p2 = ((tmp_3_fu_793_p4 != present_window_13_load_reg_2690_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_20_fu_1151_p2 = ((tmp_21_fu_1142_p4 != present_window_14_load_reg_2704_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_21_fu_1165_p2 = ((tmp_22_fu_1156_p4 != present_window_15_load_reg_2737) ? 1'b1 : 1'b0);

assign icmp_ln168_22_fu_1179_p2 = ((tmp_23_fu_1170_p4 != new_byte_reg_2773) ? 1'b1 : 1'b0);

assign icmp_ln168_24_fu_1222_p2 = ((tmp_25_fu_1213_p4 != present_window_12_load_reg_2676_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_25_fu_1242_p2 = ((tmp_26_fu_1233_p4 != present_window_13_load_reg_2690_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_26_fu_1256_p2 = ((tmp_27_fu_1247_p4 != present_window_14_load_reg_2704_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_27_fu_1270_p2 = ((tmp_28_fu_1261_p4 != present_window_15_load_reg_2737) ? 1'b1 : 1'b0);

assign icmp_ln168_28_fu_1284_p2 = ((tmp_29_fu_1275_p4 != new_byte_reg_2773) ? 1'b1 : 1'b0);

assign icmp_ln168_2_fu_828_p2 = ((tmp_4_fu_819_p4 != present_window_14_load_reg_2704_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_30_fu_1321_p2 = ((tmp_31_fu_1312_p4 != present_window_12_load_reg_2676_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_31_fu_1335_p2 = ((tmp_32_fu_1326_p4 != present_window_13_load_reg_2690_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_32_fu_1349_p2 = ((tmp_33_fu_1340_p4 != present_window_14_load_reg_2704_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_33_fu_1363_p2 = ((tmp_34_fu_1354_p4 != present_window_15_load_reg_2737) ? 1'b1 : 1'b0);

assign icmp_ln168_34_fu_1377_p2 = ((tmp_35_fu_1368_p4 != new_byte_reg_2773) ? 1'b1 : 1'b0);

assign icmp_ln168_3_fu_842_p2 = ((tmp_5_fu_833_p4 != present_window_15_load_reg_2737) ? 1'b1 : 1'b0);

assign icmp_ln168_4_fu_856_p2 = ((tmp_6_fu_847_p4 != new_byte_reg_2773) ? 1'b1 : 1'b0);

assign icmp_ln168_6_fu_903_p2 = ((tmp_9_fu_894_p4 != present_window_12_load_reg_2676_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_7_fu_939_p2 = ((tmp_s_fu_930_p4 != present_window_13_load_reg_2690_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_8_fu_965_p2 = ((tmp_7_fu_956_p4 != present_window_14_load_reg_2704_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln168_9_fu_979_p2 = ((tmp_10_fu_970_p4 != present_window_15_load_reg_2737) ? 1'b1 : 1'b0);

assign icmp_ln168_fu_766_p2 = ((tmp_2_fu_757_p4 != present_window_12_load_reg_2676_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign icmp_ln178_1_fu_1512_p2 = ((currIdx_reg_reg_2835 > zext_ln161_1_fu_1463_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_2_fu_1877_p2 = ((currIdx_reg_reg_2835 > zext_ln161_2_fu_1840_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_3_fu_2080_p2 = ((currIdx_reg_reg_2835 > zext_ln161_3_fu_2060_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_4_fu_2115_p2 = ((currIdx_reg_reg_2835 > zext_ln161_4_fu_2112_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_5_fu_2144_p2 = ((currIdx_reg_reg_2835 > zext_ln161_5_fu_2141_p1) ? 1'b1 : 1'b0);

assign icmp_ln178_fu_1431_p2 = ((currIdx_reg_reg_2835 > zext_ln161_fu_1382_p1) ? 1'b1 : 1'b0);

assign icmp_ln179_1_fu_1532_p2 = ((tmp_37_fu_1522_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_2_fu_1897_p2 = ((tmp_39_fu_1887_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_3_fu_2100_p2 = ((tmp_41_fu_2090_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_4_fu_2135_p2 = ((tmp_43_fu_2125_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_5_fu_2164_p2 = ((tmp_45_fu_2154_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_1451_p2 = ((tmp_1_fu_1441_p4 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_1_fu_1816_p2 = ((match_offset_1_fu_1811_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_2_fu_2038_p2 = ((match_offset_2_reg_3203 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_3_fu_2275_p2 = ((match_offset_3_reg_3271 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_4_fu_2302_p2 = ((match_offset_4_fu_2297_p2 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_5_fu_2467_p2 = ((match_offset_5_reg_3340 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_1773_p2 = ((match_offset_reg_3092 != 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln185_10_fu_2472_p2 = ((len_71_fu_2452_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_11_fu_2478_p2 = ((match_offset_5_reg_3340 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_1_fu_1784_p2 = ((match_offset_reg_3092 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_2_fu_1822_p2 = ((len_67_fu_1804_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_3_fu_1828_p2 = ((match_offset_1_fu_1811_p2 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_4_fu_2043_p2 = ((len_68_fu_2023_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_5_fu_2049_p2 = ((match_offset_2_reg_3203 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_6_fu_2280_p2 = ((len_69_fu_2261_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_7_fu_2286_p2 = ((match_offset_3_reg_3271 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_8_fu_2308_p2 = ((len_70_reg_3222 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln185_9_fu_2313_p2 = ((match_offset_4_fu_2297_p2 < 32'd4097) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_1778_p2 = ((len_66_fu_1766_p3 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln191_1_fu_2196_p2 = ((len_68_fu_2023_p3 > match_length_3_fu_2190_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_2_fu_2369_p2 = ((len_69_fu_2261_p3 > match_length_5_fu_2364_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_3_fu_2489_p2 = ((len_70_reg_3222 > match_length_7_reg_3352) ? 1'b1 : 1'b0);

assign icmp_ln191_4_fu_2515_p2 = ((len_71_fu_2452_p3 > match_length_9_fu_2509_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_2170_p2 = ((len_67_reg_3170 > match_length_1_reg_3235) ? 1'b1 : 1'b0);

assign icmp_ln93_fu_519_p2 = ((i_fu_298 < sub27) ? 1'b1 : 1'b0);

assign len_11_fu_879_p2 = ((tmp_8_fu_870_p4 == present_window_11_load_reg_2662_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_12_fu_914_p3 = ((len_11_fu_879_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_13_fu_922_p3 = ((done_6_fu_908_p2[0:0] == 1'b1) ? zext_ln168_1_fu_884_p1 : len_12_fu_914_p3);

assign len_14_fu_950_p2 = (len_13_fu_922_p3 + 2'd1);

assign len_15_fu_1466_p3 = ((done_7_reg_2897[0:0] == 1'b1) ? len_13_reg_2892 : len_14_reg_2903);

assign len_16_fu_1479_p2 = (zext_ln165_1_fu_1471_p1 + 3'd1);

assign len_17_fu_1485_p3 = ((done_8_fu_1475_p2[0:0] == 1'b1) ? zext_ln165_1_fu_1471_p1 : len_16_fu_1479_p2);

assign len_18_fu_1498_p2 = (len_17_fu_1485_p3 + 3'd1);

assign len_19_fu_1504_p3 = ((done_9_fu_1493_p2[0:0] == 1'b1) ? len_17_fu_1485_p3 : len_18_fu_1498_p2);

assign len_1_fu_777_p3 = ((len_fu_742_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_20_fu_1799_p2 = (len_19_reg_3104 + 3'd1);

assign len_22_fu_1016_p2 = ((tmp_12_fu_1007_p4 == present_window_11_load_reg_2662_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_23_fu_1551_p3 = ((len_22_reg_2928[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_24_fu_1558_p3 = ((done_11_fu_1546_p2[0:0] == 1'b1) ? zext_ln168_2_fu_1538_p1 : len_23_fu_1551_p3);

assign len_25_fu_1571_p2 = (len_24_fu_1558_p3 + 2'd1);

assign len_26_fu_1577_p3 = ((done_12_fu_1566_p2[0:0] == 1'b1) ? len_24_fu_1558_p3 : len_25_fu_1571_p2);

assign len_27_fu_1846_p2 = (zext_ln165_2_fu_1843_p1 + 3'd1);

assign len_28_fu_1852_p3 = ((done_13_reg_3130[0:0] == 1'b1) ? zext_ln165_2_fu_1843_p1 : len_27_fu_1846_p2);

assign len_29_fu_1863_p2 = (len_28_fu_1852_p3 + 3'd1);

assign len_2_fu_785_p3 = ((done_1_fu_771_p2[0:0] == 1'b1) ? zext_ln168_fu_747_p1 : len_1_fu_777_p3);

assign len_30_fu_1869_p3 = ((done_14_fu_1859_p2[0:0] == 1'b1) ? len_28_fu_1852_p3 : len_29_fu_1863_p2);

assign len_31_fu_2018_p2 = (len_30_reg_3187 + 3'd1);

assign len_33_fu_1109_p2 = ((tmp_18_fu_1100_p4 == present_window_11_load_reg_2662_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_34_fu_1603_p3 = ((len_33_reg_2965[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_35_fu_1610_p3 = ((done_16_fu_1598_p2[0:0] == 1'b1) ? zext_ln168_3_fu_1590_p1 : len_34_fu_1603_p3);

assign len_36_fu_1623_p2 = (len_35_fu_1610_p3 + 2'd1);

assign len_37_fu_1629_p3 = ((done_17_fu_1618_p2[0:0] == 1'b1) ? len_35_fu_1610_p3 : len_36_fu_1623_p2);

assign len_38_fu_1912_p2 = (zext_ln165_3_fu_1909_p1 + 3'd1);

assign len_39_fu_1918_p3 = ((done_18_reg_3141[0:0] == 1'b1) ? zext_ln165_3_fu_1909_p1 : len_38_fu_1912_p2);

assign len_3_fu_813_p2 = (len_2_fu_785_p3 + 2'd1);

assign len_40_fu_2063_p2 = (len_39_reg_3210 + 3'd1);

assign len_41_fu_2068_p3 = ((done_19_reg_3216[0:0] == 1'b1) ? len_39_reg_3210 : len_40_fu_2063_p2);

assign len_42_fu_2074_p2 = (len_41_fu_2068_p3 + 3'd1);

assign len_44_fu_1202_p2 = ((tmp_24_fu_1193_p4 == present_window_11_load_reg_2662_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_45_fu_1645_p3 = ((len_44_reg_3002[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_46_fu_1652_p3 = ((done_21_reg_3008[0:0] == 1'b1) ? zext_ln168_4_fu_1642_p1 : len_45_fu_1645_p3);

assign len_47_fu_1663_p2 = (len_46_fu_1652_p3 + 2'd1);

assign len_48_fu_1669_p3 = ((done_22_fu_1659_p2[0:0] == 1'b1) ? len_46_fu_1652_p3 : len_47_fu_1663_p2);

assign len_49_fu_1686_p2 = (zext_ln165_4_fu_1677_p1 + 3'd1);

assign len_4_fu_1385_p3 = ((done_2_reg_2861[0:0] == 1'b1) ? len_2_reg_2856 : len_3_reg_2867);

assign len_50_fu_1692_p3 = ((done_23_fu_1681_p2[0:0] == 1'b1) ? zext_ln165_4_fu_1677_p1 : len_49_fu_1686_p2);

assign len_51_fu_1929_p2 = (len_50_reg_3147 + 3'd1);

assign len_52_fu_1934_p3 = ((done_24_reg_3153[0:0] == 1'b1) ? len_50_reg_3147 : len_51_fu_1929_p2);

assign len_53_fu_1944_p2 = (len_52_fu_1934_p3 + 3'd1);

assign len_55_fu_1307_p2 = ((tmp_30_fu_1298_p4 == present_window_11_load_reg_2662_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign len_56_fu_1718_p3 = ((len_55_reg_3039[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign len_57_fu_1725_p3 = ((done_26_fu_1713_p2[0:0] == 1'b1) ? zext_ln168_5_fu_1705_p1 : len_56_fu_1718_p3);

assign len_58_fu_1738_p2 = (len_57_fu_1725_p3 + 2'd1);

assign len_59_fu_1744_p3 = ((done_27_fu_1733_p2[0:0] == 1'b1) ? len_57_fu_1725_p3 : len_58_fu_1738_p2);

assign len_5_fu_1398_p2 = (zext_ln165_fu_1390_p1 + 3'd1);

assign len_60_fu_2328_p2 = (zext_ln165_5_fu_2325_p1 + 3'd1);

assign len_61_fu_2334_p3 = ((done_28_reg_3164[0:0] == 1'b1) ? zext_ln165_5_fu_2325_p1 : len_60_fu_2328_p2);

assign len_62_fu_2345_p2 = (len_61_fu_2334_p3 + 3'd1);

assign len_63_fu_2351_p3 = ((done_29_fu_2341_p2[0:0] == 1'b1) ? len_61_fu_2334_p3 : len_62_fu_2345_p2);

assign len_64_fu_2447_p2 = (len_63_reg_3334 + 3'd1);

assign len_66_fu_1766_p3 = ((or_ln168_fu_1757_p2[0:0] == 1'b1) ? len_8_reg_3076 : len_9_fu_1761_p2);

assign len_67_fu_1804_p3 = ((or_ln168_5_fu_1795_p2[0:0] == 1'b1) ? len_19_reg_3104 : len_20_fu_1799_p2);

assign len_68_fu_2023_p3 = ((or_ln168_10_fu_2014_p2[0:0] == 1'b1) ? len_30_reg_3187 : len_31_fu_2018_p2);

assign len_69_fu_2261_p3 = ((or_ln168_15_fu_2257_p2[0:0] == 1'b1) ? len_41_reg_3251 : len_42_reg_3256);

assign len_6_fu_1404_p3 = ((done_3_fu_1394_p2[0:0] == 1'b1) ? zext_ln165_fu_1390_p1 : len_5_fu_1398_p2);

assign len_70_fu_1950_p3 = ((or_ln168_20_fu_1940_p2[0:0] == 1'b1) ? len_52_fu_1934_p3 : len_53_fu_1944_p2);

assign len_71_fu_2452_p3 = ((or_ln168_25_fu_2443_p2[0:0] == 1'b1) ? len_63_reg_3334 : len_64_fu_2447_p2);

assign len_7_fu_1417_p2 = (len_6_fu_1404_p3 + 3'd1);

assign len_8_fu_1423_p3 = ((done_4_fu_1412_p2[0:0] == 1'b1) ? len_6_fu_1404_p3 : len_7_fu_1417_p2);

assign len_9_fu_1761_p2 = (len_8_reg_3076 + 3'd1);

assign len_fu_742_p2 = ((trunc_ln168_fu_739_p1 == present_window_11_load_reg_2662_pp0_iter1_reg) ? 1'b1 : 1'b0);

assign match_length_11_fu_2590_p3 = ((and_ln191_5_reg_3383[0:0] == 1'b1) ? len_71_reg_3368 : match_length_9_reg_3378);

assign match_length_1_fu_1988_p3 = ((and_ln191_fu_1982_p2[0:0] == 1'b1) ? len_66_fu_1766_p3 : 3'd0);

assign match_length_3_fu_2190_p3 = ((and_ln191_1_fu_2185_p2[0:0] == 1'b1) ? len_67_reg_3170 : match_length_1_reg_3235);

assign match_length_5_fu_2364_p3 = ((and_ln191_2_reg_3313[0:0] == 1'b1) ? len_68_reg_3246 : match_length_3_reg_3308);

assign match_length_7_fu_2403_p3 = ((and_ln191_3_fu_2397_p2[0:0] == 1'b1) ? len_69_fu_2261_p3 : match_length_5_fu_2364_p3);

assign match_length_9_fu_2509_p3 = ((and_ln191_4_fu_2504_p2[0:0] == 1'b1) ? len_70_reg_3222 : match_length_7_reg_3352);

assign match_offset_1_fu_1811_p2 = ($signed(sub_ln179_1_reg_3115) + $signed(32'd4294967295));

assign match_offset_2_fu_1903_p2 = ($signed(sub_ln179_2_fu_1882_p2) + $signed(32'd4294967295));

assign match_offset_3_fu_2106_p2 = ($signed(sub_ln179_3_fu_2085_p2) + $signed(32'd4294967295));

assign match_offset_4_fu_2297_p2 = ($signed(sub_ln179_4_reg_3283) + $signed(32'd4294967295));

assign match_offset_5_fu_2359_p2 = ($signed(sub_ln179_5_reg_3298) + $signed(32'd4294967295));

assign match_offset_fu_1457_p2 = ($signed(sub_ln179_fu_1436_p2) + $signed(32'd4294967295));

assign or_ln168_10_fu_2014_p2 = (icmp_ln168_16_reg_2955 | done_14_reg_3182);

assign or_ln168_15_fu_2257_p2 = (icmp_ln168_22_reg_2992_pp0_iter2_reg | done_19_reg_3216);

assign or_ln168_20_fu_1940_p2 = (icmp_ln168_28_reg_3029 | done_24_reg_3153);

assign or_ln168_25_fu_2443_p2 = (icmp_ln168_34_reg_3066_pp0_iter2_reg | done_29_reg_3329);

assign or_ln168_5_fu_1795_p2 = (icmp_ln168_10_reg_2918 | done_9_reg_3099);

assign or_ln168_fu_1757_p2 = (icmp_ln168_4_reg_2882 | done_4_reg_3071);

assign or_ln185_1_fu_1834_p2 = (icmp_ln185_3_fu_1828_p2 | icmp_ln185_2_fu_1822_p2);

assign or_ln185_2_fu_2054_p2 = (icmp_ln185_5_fu_2049_p2 | icmp_ln185_4_fu_2043_p2);

assign or_ln185_3_fu_2291_p2 = (icmp_ln185_7_fu_2286_p2 | icmp_ln185_6_fu_2280_p2);

assign or_ln185_4_fu_2319_p2 = (icmp_ln185_9_fu_2313_p2 | icmp_ln185_8_fu_2308_p2);

assign or_ln185_5_fu_2483_p2 = (icmp_ln185_11_fu_2478_p2 | icmp_ln185_10_fu_2472_p2);

assign or_ln185_fu_1789_p2 = (icmp_ln185_fu_1778_p2 | icmp_ln185_1_fu_1784_p2);

assign or_ln191_1_fu_2553_p2 = (and_ln191_3_reg_3347 | and_ln191_2_reg_3313);

assign or_ln191_2_fu_2244_p2 = (and_ln191_reg_3230 | and_ln191_1_fu_2185_p2);

assign or_ln191_3_fu_2577_p2 = (or_ln191_fu_2549_p2 | or_ln191_1_fu_2553_p2);

assign or_ln191_fu_2549_p2 = (and_ln191_5_reg_3383 | and_ln191_4_reg_3373);

assign present_window_11_out = present_window_11_load_reg_2662_pp0_iter2_reg;

assign present_window_12_out = present_window_12_load_reg_2676_pp0_iter2_reg;

assign present_window_13_out = present_window_13_load_reg_2690_pp0_iter2_reg;

assign present_window_14_cast_fu_532_p1 = present_window_14_fu_314;

assign present_window_14_out = present_window_14_load_reg_2704_pp0_iter2_reg;

assign present_window_15_out = present_window_15_load_reg_2737_pp0_iter2_reg;

assign select_ln191_1_fu_2563_p3 = ((and_ln191_5_reg_3383[0:0] == 1'b1) ? trunc_ln191_2_fu_2557_p1 : trunc_ln191_3_fu_2560_p1);

assign select_ln191_2_fu_2428_p3 = ((and_ln191_3_fu_2397_p2[0:0] == 1'b1) ? trunc_ln191_4_fu_2422_p1 : trunc_ln191_5_fu_2425_p1);

assign select_ln191_3_fu_2570_p3 = ((or_ln191_fu_2549_p2[0:0] == 1'b1) ? select_ln191_1_fu_2563_p3 : select_ln191_2_reg_3363);

assign select_ln191_4_fu_2249_p3 = ((or_ln191_2_fu_2244_p2[0:0] == 1'b1) ? select_ln191_fu_2236_p3 : 16'd0);

assign select_ln191_5_fu_2583_p3 = ((or_ln191_3_fu_2577_p2[0:0] == 1'b1) ? select_ln191_3_fu_2570_p3 : select_ln191_4_reg_3319);

assign select_ln191_fu_2236_p3 = ((and_ln191_1_fu_2185_p2[0:0] == 1'b1) ? trunc_ln191_fu_2230_p1 : trunc_ln191_1_fu_2233_p1);

assign shl_ln1_fu_584_p3 = {{trunc_ln119_fu_581_p1}, {3'd0}};

assign shl_ln_fu_573_p3 = {{trunc_ln118_fu_570_p1}, {4'd0}};

assign sub_ln179_1_fu_1517_p2 = (currIdx_reg_reg_2835 - zext_ln161_1_fu_1463_p1);

assign sub_ln179_2_fu_1882_p2 = (currIdx_reg_reg_2835 - zext_ln161_2_fu_1840_p1);

assign sub_ln179_3_fu_2085_p2 = (currIdx_reg_reg_2835 - zext_ln161_3_fu_2060_p1);

assign sub_ln179_4_fu_2120_p2 = (currIdx_reg_reg_2835 - zext_ln161_4_fu_2112_p1);

assign sub_ln179_5_fu_2149_p2 = (currIdx_reg_reg_2835 - zext_ln161_5_fu_2141_p1);

assign sub_ln179_fu_1436_p2 = (currIdx_reg_reg_2835 - zext_ln161_fu_1382_p1);

assign tmp1_fu_592_p2 = (present_window_13_load_reg_2690 + present_window_14_load_reg_2704);

assign tmp_10_fu_970_p4 = {{dictReadValue_reg_reg_2784[107:100]}};

assign tmp_11_fu_984_p4 = {{dictReadValue_reg_reg_2784[115:108]}};

assign tmp_12_fu_1007_p4 = {{dictReadValue_reg_reg_2784[143:136]}};

assign tmp_13_fu_1021_p4 = {{dictReadValue_reg_reg_2784[151:144]}};

assign tmp_14_fu_1035_p4 = {{dictReadValue_reg_reg_2784[159:152]}};

assign tmp_15_fu_1049_p4 = {{dictReadValue_reg_reg_2784[167:160]}};

assign tmp_16_fu_1063_p4 = {{dictReadValue_reg_reg_2784[175:168]}};

assign tmp_17_fu_1077_p4 = {{dictReadValue_reg_reg_2784[183:176]}};

assign tmp_18_fu_1100_p4 = {{dictReadValue_reg_reg_2784[211:204]}};

assign tmp_19_fu_1114_p4 = {{dictReadValue_reg_reg_2784[219:212]}};

assign tmp_1_fu_1441_p4 = {{sub_ln179_fu_1436_p2[31:16]}};

assign tmp_20_fu_1128_p4 = {{dictReadValue_reg_reg_2784[227:220]}};

assign tmp_21_fu_1142_p4 = {{dictReadValue_reg_reg_2784[235:228]}};

assign tmp_22_fu_1156_p4 = {{dictReadValue_reg_reg_2784[243:236]}};

assign tmp_23_fu_1170_p4 = {{dictReadValue_reg_reg_2784[251:244]}};

assign tmp_24_fu_1193_p4 = {{dictReadValue_reg_reg_2784[279:272]}};

assign tmp_25_fu_1213_p4 = {{dictReadValue_reg_reg_2784[287:280]}};

assign tmp_26_fu_1233_p4 = {{dictReadValue_reg_reg_2784[295:288]}};

assign tmp_27_fu_1247_p4 = {{dictReadValue_reg_reg_2784[303:296]}};

assign tmp_28_fu_1261_p4 = {{dictReadValue_reg_reg_2784[311:304]}};

assign tmp_29_fu_1275_p4 = {{dictReadValue_reg_reg_2784[319:312]}};

assign tmp_2_fu_757_p4 = {{dictReadValue_reg_reg_2784[15:8]}};

assign tmp_30_fu_1298_p4 = {{dictReadValue_reg_reg_2784[347:340]}};

assign tmp_31_fu_1312_p4 = {{dictReadValue_reg_reg_2784[355:348]}};

assign tmp_32_fu_1326_p4 = {{dictReadValue_reg_reg_2784[363:356]}};

assign tmp_33_fu_1340_p4 = {{dictReadValue_reg_reg_2784[371:364]}};

assign tmp_34_fu_1354_p4 = {{dictReadValue_reg_reg_2784[379:372]}};

assign tmp_35_fu_1368_p4 = {{dictReadValue_reg_reg_2784[387:380]}};

assign tmp_36_fu_2007_p3 = len_67_reg_3170[32'd2];

assign tmp_37_fu_1522_p4 = {{sub_ln179_1_fu_1517_p2[31:16]}};

assign tmp_38_fu_2030_p3 = len_68_fu_2023_p3[32'd2];

assign tmp_39_fu_1887_p4 = {{sub_ln179_2_fu_1882_p2[31:16]}};

assign tmp_3_fu_793_p4 = {{dictReadValue_reg_reg_2784[23:16]}};

assign tmp_40_fu_2267_p3 = len_69_fu_2261_p3[32'd2];

assign tmp_41_fu_2090_p4 = {{sub_ln179_3_fu_2085_p2[31:16]}};

assign tmp_42_fu_2436_p3 = len_70_reg_3222[32'd2];

assign tmp_43_fu_2125_p4 = {{sub_ln179_4_fu_2120_p2[31:16]}};

assign tmp_44_fu_2459_p3 = len_71_fu_2452_p3[32'd2];

assign tmp_45_fu_2154_p4 = {{sub_ln179_5_fu_2149_p2[31:16]}};

assign tmp_46_fu_1969_p3 = len_66_fu_1766_p3[32'd2];

assign tmp_4_fu_819_p4 = {{dictReadValue_reg_reg_2784[31:24]}};

assign tmp_5_fu_833_p4 = {{dictReadValue_reg_reg_2784[39:32]}};

assign tmp_6_fu_847_p4 = {{dictReadValue_reg_reg_2784[47:40]}};

assign tmp_7_fu_956_p4 = {{dictReadValue_reg_reg_2784[99:92]}};

assign tmp_8_fu_870_p4 = {{dictReadValue_reg_reg_2784[75:68]}};

assign tmp_9_fu_894_p4 = {{dictReadValue_reg_reg_2784[83:76]}};

assign tmp_fu_596_p3 = {{tmp1_fu_592_p2}, {2'd0}};

assign tmp_s_fu_930_p4 = {{dictReadValue_reg_reg_2784[91:84]}};

assign trunc_ln111_fu_621_p1 = add_ln123_5_fu_616_p2[1:0];

assign trunc_ln118_fu_570_p1 = present_window_11_load_reg_2662[5:0];

assign trunc_ln119_fu_581_p1 = present_window_12_load_reg_2676[6:0];

assign trunc_ln127_fu_695_p1 = dictReadValue_reg_fu_672_p11[339:0];

assign trunc_ln132_fu_709_p1 = currIdx_reg_fu_704_p2[19:0];

assign trunc_ln168_fu_739_p1 = dictReadValue_reg_reg_2784[7:0];

assign trunc_ln191_1_fu_2233_p1 = match_offset_reg_3092[15:0];

assign trunc_ln191_2_fu_2557_p1 = match_offset_5_reg_3340[15:0];

assign trunc_ln191_3_fu_2560_p1 = match_offset_4_reg_3324[15:0];

assign trunc_ln191_4_fu_2422_p1 = match_offset_3_reg_3271[15:0];

assign trunc_ln191_5_fu_2425_p1 = match_offset_2_reg_3203[15:0];

assign trunc_ln191_fu_2230_p1 = match_offset_1_reg_3177[15:0];

assign zext_ln111_fu_638_p1 = lshr_ln1_reg_2732;

assign zext_ln118_fu_524_p1 = present_window_11_fu_302;

assign zext_ln119_fu_528_p1 = present_window_12_fu_306;

assign zext_ln123_1_fu_554_p1 = add_ln123_fu_548_p2;

assign zext_ln123_fu_544_p1 = factor_fu_536_p3;

assign zext_ln148_fu_2595_p1 = match_length_11_fu_2590_p3;

assign zext_ln161_1_fu_1463_p1 = compareIdx_1_reg_2887;

assign zext_ln161_2_fu_1840_p1 = compareIdx_2_reg_2923;

assign zext_ln161_3_fu_2060_p1 = compareIdx_3_reg_2960;

assign zext_ln161_4_fu_2112_p1 = compareIdx_4_reg_2997;

assign zext_ln161_5_fu_2141_p1 = compareIdx_5_reg_3034;

assign zext_ln161_fu_1382_p1 = compareIdx_reg_2851;

assign zext_ln165_1_fu_1471_p1 = len_15_fu_1466_p3;

assign zext_ln165_2_fu_1843_p1 = len_26_reg_3125;

assign zext_ln165_3_fu_1909_p1 = len_37_reg_3136;

assign zext_ln165_4_fu_1677_p1 = len_48_fu_1669_p3;

assign zext_ln165_5_fu_2325_p1 = len_59_reg_3159;

assign zext_ln165_fu_1390_p1 = len_4_fu_1385_p3;

assign zext_ln168_1_fu_884_p1 = len_11_fu_879_p2;

assign zext_ln168_2_fu_1538_p1 = len_22_reg_2928;

assign zext_ln168_3_fu_1590_p1 = len_33_reg_2965;

assign zext_ln168_4_fu_1642_p1 = len_44_reg_3002;

assign zext_ln168_5_fu_1705_p1 = len_55_reg_3039;

assign zext_ln168_fu_747_p1 = len_fu_742_p2;

endmodule //lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress
