-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_empty_n : IN STD_LOGIC;
    inStream_read : OUT STD_LOGIC;
    compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    compressdStream_full_n : IN STD_LOGIC;
    compressdStream_write : OUT STD_LOGIC;
    compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size : IN STD_LOGIC_VECTOR (31 downto 0);
    input_size_c2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    input_size_c2_full_n : IN STD_LOGIC;
    input_size_c2_write : OUT STD_LOGIC;
    input_size_c2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    input_size_c2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_FFFFFFC0 : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal input_size_c2_blk_n : STD_LOGIC;
    signal input_size_read_reg_414 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal icmp_ln64_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln64_reg_509 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub27_fu_276_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub27_reg_528 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln93_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln93_reg_533 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln82_fu_332_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_reg_542 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln82_1_fu_340_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_1_reg_547 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_2_fu_348_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_2_reg_552 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_3_fu_356_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_3_reg_557 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_4_fu_364_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln82_4_reg_562 : STD_LOGIC_VECTOR (7 downto 0);
    signal dict_ce0 : STD_LOGIC;
    signal dict_q0 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dict_ce1 : STD_LOGIC;
    signal dict_we1 : STD_LOGIC;
    signal dict_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_1_ce0 : STD_LOGIC;
    signal dict_1_q0 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dict_1_ce1 : STD_LOGIC;
    signal dict_1_we1 : STD_LOGIC;
    signal dict_1_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_2_ce0 : STD_LOGIC;
    signal dict_2_q0 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dict_2_ce1 : STD_LOGIC;
    signal dict_2_we1 : STD_LOGIC;
    signal dict_2_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_3_ce0 : STD_LOGIC;
    signal dict_3_q0 : STD_LOGIC_VECTOR (407 downto 0);
    signal dict_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal dict_3_ce1 : STD_LOGIC;
    signal dict_3_we1 : STD_LOGIC;
    signal dict_3_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_4_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_4_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_3_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_3_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_2_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_2_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_1_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_1_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx48_promoted187_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx48_promoted187_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx42_3_promoted185_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx42_3_promoted185_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx71_promoted183_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx71_promoted183_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx61_promoted181_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx61_promoted181_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx54_promoted179_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx54_promoted179_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce0 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_we1 : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_d1 : STD_LOGIC_VECTOR (407 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_15_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_15_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_14_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_14_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_13_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_13_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_12_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_12_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_11_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_11_out_ap_vld : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_done : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_idle : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_ready : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_inStream_read : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_write : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start_reg : STD_LOGIC := '0';
    signal present_window_4_loc_fu_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_3_loc_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_2_loc_fu_108 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_1_loc_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal present_window_loc_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx48_promoted187_loc_fu_96 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx42_3_promoted185_loc_fu_92 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx71_promoted183_loc_fu_88 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx61_promoted181_loc_fu_84 : STD_LOGIC_VECTOR (7 downto 0);
    signal arrayidx54_promoted179_loc_fu_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_block_state9_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dict_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_3_ce1 : OUT STD_LOGIC;
        dict_3_we1 : OUT STD_LOGIC;
        dict_3_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        dict_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_2_ce1 : OUT STD_LOGIC;
        dict_2_we1 : OUT STD_LOGIC;
        dict_2_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        dict_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_1_ce1 : OUT STD_LOGIC;
        dict_1_we1 : OUT STD_LOGIC;
        dict_1_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        dict_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_ce1 : OUT STD_LOGIC;
        dict_we1 : OUT STD_LOGIC;
        dict_d1 : OUT STD_LOGIC_VECTOR (407 downto 0) );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        present_window_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_4_out_ap_vld : OUT STD_LOGIC;
        present_window_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_3_out_ap_vld : OUT STD_LOGIC;
        present_window_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_2_out_ap_vld : OUT STD_LOGIC;
        present_window_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_1_out_ap_vld : OUT STD_LOGIC;
        present_window_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_out_ap_vld : OUT STD_LOGIC;
        arrayidx48_promoted187_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx48_promoted187_out_ap_vld : OUT STD_LOGIC;
        arrayidx42_3_promoted185_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx42_3_promoted185_out_ap_vld : OUT STD_LOGIC;
        arrayidx71_promoted183_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx71_promoted183_out_ap_vld : OUT STD_LOGIC;
        arrayidx61_promoted181_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx61_promoted181_out_ap_vld : OUT STD_LOGIC;
        arrayidx54_promoted179_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        arrayidx54_promoted179_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        arrayidx48_promoted187_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx42_3_promoted185_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx71_promoted183_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx61_promoted181_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        arrayidx54_promoted179_reload : IN STD_LOGIC_VECTOR (7 downto 0);
        sub27 : IN STD_LOGIC_VECTOR (31 downto 0);
        dict_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_3_ce0 : OUT STD_LOGIC;
        dict_3_q0 : IN STD_LOGIC_VECTOR (407 downto 0);
        dict_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_3_ce1 : OUT STD_LOGIC;
        dict_3_we1 : OUT STD_LOGIC;
        dict_3_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        dict_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_2_ce0 : OUT STD_LOGIC;
        dict_2_q0 : IN STD_LOGIC_VECTOR (407 downto 0);
        dict_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_2_ce1 : OUT STD_LOGIC;
        dict_2_we1 : OUT STD_LOGIC;
        dict_2_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        dict_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_1_ce0 : OUT STD_LOGIC;
        dict_1_q0 : IN STD_LOGIC_VECTOR (407 downto 0);
        dict_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_1_ce1 : OUT STD_LOGIC;
        dict_1_we1 : OUT STD_LOGIC;
        dict_1_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        dict_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_ce0 : OUT STD_LOGIC;
        dict_q0 : IN STD_LOGIC_VECTOR (407 downto 0);
        dict_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        dict_ce1 : OUT STD_LOGIC;
        dict_we1 : OUT STD_LOGIC;
        dict_d1 : OUT STD_LOGIC_VECTOR (407 downto 0);
        present_window_15_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_15_out_ap_vld : OUT STD_LOGIC;
        present_window_14_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_14_out_ap_vld : OUT STD_LOGIC;
        present_window_13_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_13_out_ap_vld : OUT STD_LOGIC;
        present_window_12_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_12_out_ap_vld : OUT STD_LOGIC;
        present_window_11_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        present_window_11_out_ap_vld : OUT STD_LOGIC );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        select_ln82_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln82_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln82_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln82_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        select_ln82 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        inStream_empty_n : IN STD_LOGIC;
        inStream_read : OUT STD_LOGIC;
        compressdStream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compressdStream_full_n : IN STD_LOGIC;
        compressdStream_write : OUT STD_LOGIC;
        compressdStream_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        compressdStream_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s_dict_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (407 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (407 downto 0) );
    end component;



begin
    dict_U : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s_dict_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 408,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address0,
        ce0 => dict_ce0,
        q0 => dict_q0,
        address1 => dict_address1,
        ce1 => dict_ce1,
        we1 => dict_we1,
        d1 => dict_d1);

    dict_1_U : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s_dict_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 408,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address0,
        ce0 => dict_1_ce0,
        q0 => dict_1_q0,
        address1 => dict_1_address1,
        ce1 => dict_1_ce1,
        we1 => dict_1_we1,
        d1 => dict_1_d1);

    dict_2_U : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s_dict_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 408,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address0,
        ce0 => dict_2_ce0,
        q0 => dict_2_q0,
        address1 => dict_2_address1,
        ce1 => dict_2_ce1,
        we1 => dict_2_we1,
        d1 => dict_2_d1);

    dict_3_U : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_s_dict_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 408,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address0,
        ce0 => dict_3_ce0,
        q0 => dict_3_q0,
        address1 => dict_3_address1,
        ce1 => dict_3_ce1,
        we1 => dict_3_we1,
        d1 => dict_3_d1);

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_ready,
        dict_3_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_address1,
        dict_3_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_ce1,
        dict_3_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_we1,
        dict_3_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_d1,
        dict_2_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_address1,
        dict_2_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_ce1,
        dict_2_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_we1,
        dict_2_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_d1,
        dict_1_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_address1,
        dict_1_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_ce1,
        dict_1_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_we1,
        dict_1_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_d1,
        dict_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_address1,
        dict_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_ce1,
        dict_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_we1,
        dict_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_d1);

    grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_inStream_read,
        present_window_4_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_4_out,
        present_window_4_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_4_out_ap_vld,
        present_window_3_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_3_out,
        present_window_3_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_3_out_ap_vld,
        present_window_2_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_2_out,
        present_window_2_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_2_out_ap_vld,
        present_window_1_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_1_out,
        present_window_1_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_1_out_ap_vld,
        present_window_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_out,
        present_window_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_out_ap_vld,
        arrayidx48_promoted187_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx48_promoted187_out,
        arrayidx48_promoted187_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx48_promoted187_out_ap_vld,
        arrayidx42_3_promoted185_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx42_3_promoted185_out,
        arrayidx42_3_promoted185_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx42_3_promoted185_out_ap_vld,
        arrayidx71_promoted183_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx71_promoted183_out,
        arrayidx71_promoted183_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx71_promoted183_out_ap_vld,
        arrayidx61_promoted181_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx61_promoted181_out,
        arrayidx61_promoted181_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx61_promoted181_out_ap_vld,
        arrayidx54_promoted179_out => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx54_promoted179_out,
        arrayidx54_promoted179_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx54_promoted179_out_ap_vld);

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_inStream_read,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_write,
        compressdStream_num_data_valid => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid,
        compressdStream_fifo_cap => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap,
        arrayidx48_promoted187_reload => arrayidx48_promoted187_loc_fu_96,
        arrayidx42_3_promoted185_reload => arrayidx42_3_promoted185_loc_fu_92,
        arrayidx71_promoted183_reload => arrayidx71_promoted183_loc_fu_88,
        arrayidx61_promoted181_reload => arrayidx61_promoted181_loc_fu_84,
        arrayidx54_promoted179_reload => arrayidx54_promoted179_loc_fu_80,
        sub27 => sub27_reg_528,
        dict_3_address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address0,
        dict_3_ce0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce0,
        dict_3_q0 => dict_3_q0,
        dict_3_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address1,
        dict_3_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce1,
        dict_3_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_we1,
        dict_3_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_d1,
        dict_2_address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address0,
        dict_2_ce0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce0,
        dict_2_q0 => dict_2_q0,
        dict_2_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address1,
        dict_2_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce1,
        dict_2_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_we1,
        dict_2_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_d1,
        dict_1_address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address0,
        dict_1_ce0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce0,
        dict_1_q0 => dict_1_q0,
        dict_1_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address1,
        dict_1_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce1,
        dict_1_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_we1,
        dict_1_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_d1,
        dict_address0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address0,
        dict_ce0 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce0,
        dict_q0 => dict_q0,
        dict_address1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address1,
        dict_ce1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce1,
        dict_we1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_we1,
        dict_d1 => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_d1,
        present_window_15_out => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_15_out,
        present_window_15_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_15_out_ap_vld,
        present_window_14_out => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_14_out,
        present_window_14_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_14_out_ap_vld,
        present_window_13_out => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_13_out,
        present_window_13_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_13_out_ap_vld,
        present_window_12_out => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_12_out,
        present_window_12_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_12_out_ap_vld,
        present_window_11_out => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_11_out,
        present_window_11_out_ap_vld => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_11_out_ap_vld);

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_ready,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_write,
        compressdStream_num_data_valid => compressdStream_num_data_valid,
        compressdStream_fifo_cap => compressdStream_fifo_cap,
        select_ln82_4 => select_ln82_4_reg_562,
        select_ln82_3 => select_ln82_3_reg_557,
        select_ln82_2 => select_ln82_2_reg_552,
        select_ln82_1 => select_ln82_1_reg_547,
        select_ln82 => select_ln82_reg_542);

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208 : component lz4CompressEngineRun_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start,
        ap_done => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_done,
        ap_idle => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_idle,
        ap_ready => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_ready,
        inStream_dout => inStream_dout,
        inStream_empty_n => inStream_empty_n,
        inStream_read => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_inStream_read,
        compressdStream_din => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_din,
        compressdStream_full_n => compressdStream_full_n,
        compressdStream_write => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_write,
        compressdStream_num_data_valid => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid,
        compressdStream_fifo_cap => grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_ready = ap_const_logic_1)) then 
                    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx42_3_promoted185_out_ap_vld = ap_const_logic_1))) then
                arrayidx42_3_promoted185_loc_fu_92 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx42_3_promoted185_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx48_promoted187_out_ap_vld = ap_const_logic_1))) then
                arrayidx48_promoted187_loc_fu_96 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx48_promoted187_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx54_promoted179_out_ap_vld = ap_const_logic_1))) then
                arrayidx54_promoted179_loc_fu_80 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx54_promoted179_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx61_promoted181_out_ap_vld = ap_const_logic_1))) then
                arrayidx61_promoted181_loc_fu_84 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx61_promoted181_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx71_promoted183_out_ap_vld = ap_const_logic_1))) then
                arrayidx71_promoted183_loc_fu_88 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_arrayidx71_promoted183_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                icmp_ln64_reg_509 <= icmp_ln64_fu_216_p2;
                input_size_read_reg_414 <= input_size;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                icmp_ln93_reg_533 <= icmp_ln93_fu_282_p2;
                sub27_reg_528 <= sub27_fu_276_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_1_out_ap_vld = ap_const_logic_1))) then
                present_window_1_loc_fu_104 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_2_out_ap_vld = ap_const_logic_1))) then
                present_window_2_loc_fu_108 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_3_out_ap_vld = ap_const_logic_1))) then
                present_window_3_loc_fu_112 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_4_out_ap_vld = ap_const_logic_1))) then
                present_window_4_loc_fu_116 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_4_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_out_ap_vld = ap_const_logic_1))) then
                present_window_loc_fu_100 <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_present_window_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                select_ln82_1_reg_547 <= select_ln82_1_fu_340_p3;
                select_ln82_2_reg_552 <= select_ln82_2_fu_348_p3;
                select_ln82_3_reg_557 <= select_ln82_3_fu_356_p3;
                select_ln82_4_reg_562 <= select_ln82_4_fu_364_p3;
                select_ln82_reg_542 <= select_ln82_fu_332_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, icmp_ln64_fu_216_p2, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_done, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_block_state9_on_subcall_done, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln64_fu_216_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((icmp_ln64_fu_216_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state3_on_subcall_done)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_done)
    begin
        if ((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_done)
    begin
        if ((grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state9_on_subcall_done)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, input_size_c2_full_n)
    begin
                ap_block_state1 <= ((input_size_c2_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_done, grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_done = ap_const_logic_0) or (grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_done = ap_const_logic_0));
    end process;


    ap_block_state9_on_subcall_done_assign_proc : process(icmp_ln64_reg_509, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_done)
    begin
                ap_block_state9_on_subcall_done <= ((icmp_ln64_reg_509 = ap_const_lv1_0) and (grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state9, ap_block_state9_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    compressdStream_din_assign_proc : process(icmp_ln64_reg_509, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_din, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_din, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_din, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if (((icmp_ln64_reg_509 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_din;
        else 
            compressdStream_din <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_din;
        end if; 
    end process;


    compressdStream_write_assign_proc : process(icmp_ln64_reg_509, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_write, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_write, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_write, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if (((icmp_ln64_reg_509 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_compressdStream_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            compressdStream_write <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_write;
        else 
            compressdStream_write <= ap_const_logic_0;
        end if; 
    end process;


    dict_1_address1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_address1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_1_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_1_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_address1;
        else 
            dict_1_address1 <= "XXXXXXXX";
        end if; 
    end process;


    dict_1_ce0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_1_ce0 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce0;
        else 
            dict_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dict_1_ce1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_ce1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_1_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_1_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_ce1;
        else 
            dict_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_1_d1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_d1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_1_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_1_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_d1;
        else 
            dict_1_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dict_1_we1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_we1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_1_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_1_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_1_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_1_we1;
        else 
            dict_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_2_address1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_address1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_2_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_2_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_address1;
        else 
            dict_2_address1 <= "XXXXXXXX";
        end if; 
    end process;


    dict_2_ce0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_2_ce0 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce0;
        else 
            dict_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dict_2_ce1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_ce1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_2_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_2_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_ce1;
        else 
            dict_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_2_d1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_d1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_2_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_2_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_d1;
        else 
            dict_2_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dict_2_we1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_we1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_2_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_2_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_2_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_2_we1;
        else 
            dict_2_we1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_3_address1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_address1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_3_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_3_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_address1;
        else 
            dict_3_address1 <= "XXXXXXXX";
        end if; 
    end process;


    dict_3_ce0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_3_ce0 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce0;
        else 
            dict_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dict_3_ce1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_ce1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_3_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_3_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_ce1;
        else 
            dict_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_3_d1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_d1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_3_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_3_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_d1;
        else 
            dict_3_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dict_3_we1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_we1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_3_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_3_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_3_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_3_we1;
        else 
            dict_3_we1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_address1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_address1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_address1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_address1;
        else 
            dict_address1 <= "XXXXXXXX";
        end if; 
    end process;


    dict_ce0_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_ce0 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce0;
        else 
            dict_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dict_ce1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_ce1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_ce1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_ce1;
        else 
            dict_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    dict_d1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_d1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_d1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_d1;
        else 
            dict_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    dict_we1_assign_proc : process(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_we1, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            dict_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_dict_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            dict_we1 <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_dict_we1;
        else 
            dict_we1 <= ap_const_logic_0;
        end if; 
    end process;

    grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_dict_flush_fu_150_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0_proc : process(compressdStream_fifo_cap)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_fifo_cap;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0_i) := compressdStream_fifo_cap(32-1-grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_fifo_cap0 <= resvalue(32-1 downto 0);
    end process;

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0_proc : process(compressdStream_num_data_valid)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_num_data_valid;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0_i) := compressdStream_num_data_valid(32-1-grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_compressdStream_num_data_valid0 <= resvalue(32-1 downto 0);
    end process;

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_leftover_fu_197_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_ap_start_reg;
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0_proc : process(compressdStream_fifo_cap)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_fifo_cap;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0_i) := compressdStream_fifo_cap(32-1-grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_fifo_cap0 <= resvalue(32-1 downto 0);
    end process;

    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0(4 - 1 downto 0);
    
    grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0_proc : process(compressdStream_num_data_valid)
    variable vlo_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable vhi_cpy : STD_LOGIC_VECTOR(32+32 - 1 downto 0);
    variable v0_cpy : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0_i : integer;
    variable section : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable tmp_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    variable resvalue, res_value, res_mask : STD_LOGIC_VECTOR(32 - 1 downto 0);
    begin
        vlo_cpy := (others => '0');
        vlo_cpy(5 - 1 downto 0) := ap_const_lv32_0(5 - 1 downto 0);
        vhi_cpy := (others => '0');
        vhi_cpy(5 - 1 downto 0) := ap_const_lv32_3(5 - 1 downto 0);
        v0_cpy := compressdStream_num_data_valid;
        if (vlo_cpy(5 - 1 downto 0) > vhi_cpy(5 - 1 downto 0)) then
            vhi_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_3(5-1 downto 0)));
            vlo_cpy(5-1 downto 0) := std_logic_vector(32-1-unsigned(ap_const_lv32_0(5-1 downto 0)));
            for grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0_i in 0 to 32-1 loop
                v0_cpy(grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0_i) := compressdStream_num_data_valid(32-1-grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0_i);
            end loop;
        end if;
        res_value := std_logic_vector(shift_right(unsigned(v0_cpy), to_integer(unsigned('0' & vlo_cpy(5-1 downto 0)))));

        section := (others=>'0');
        section(5-1 downto 0) := std_logic_vector(unsigned(vhi_cpy(5-1 downto 0)) - unsigned(vlo_cpy(5-1 downto 0)));
        tmp_mask := (others => '1');
        res_mask := std_logic_vector(shift_left(unsigned(tmp_mask),to_integer(unsigned('0' & section(31-1 downto 0)))));
        res_mask := res_mask(32-2 downto 0) & '0';
        resvalue := res_value and not res_mask;
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_compressdStream_num_data_valid0 <= resvalue(32-1 downto 0);
    end process;

    icmp_ln64_fu_216_p2 <= "1" when (input_size = ap_const_lv32_0) else "0";
    icmp_ln93_fu_282_p2 <= "1" when (unsigned(sub27_fu_276_p2) > unsigned(ap_const_lv32_5)) else "0";

    inStream_read_assign_proc : process(icmp_ln64_reg_509, grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_inStream_read, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_inStream_read, grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_inStream_read, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state9)
    begin
        if (((icmp_ln64_reg_509 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_left_bytes_fu_208_inStream_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_inStream_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            inStream_read <= grp_lzCompress_6_4_65536_6_1_1024_64_Outline_VITIS_LOOP_84_2_fu_158_inStream_read;
        else 
            inStream_read <= ap_const_logic_0;
        end if; 
    end process;


    input_size_c2_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, input_size_c2_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_c2_blk_n <= input_size_c2_full_n;
        else 
            input_size_c2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_size_c2_din <= input_size;

    input_size_c2_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_size_c2_write <= ap_const_logic_1;
        else 
            input_size_c2_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(ap_CS_fsm_state9, ap_block_state9_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln82_1_fu_340_p3 <= 
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_14_out when (icmp_ln93_reg_533(0) = '1') else 
        present_window_3_loc_fu_112;
    select_ln82_2_fu_348_p3 <= 
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_13_out when (icmp_ln93_reg_533(0) = '1') else 
        present_window_2_loc_fu_108;
    select_ln82_3_fu_356_p3 <= 
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_12_out when (icmp_ln93_reg_533(0) = '1') else 
        present_window_1_loc_fu_104;
    select_ln82_4_fu_364_p3 <= 
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_11_out when (icmp_ln93_reg_533(0) = '1') else 
        present_window_loc_fu_100;
    select_ln82_fu_332_p3 <= 
        grp_lzCompress_6_4_65536_6_1_1024_64_Pipeline_lz_compress_fu_174_present_window_15_out when (icmp_ln93_reg_533(0) = '1') else 
        present_window_4_loc_fu_116;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub27_fu_276_p2 <= std_logic_vector(unsigned(input_size_read_reg_414) + unsigned(ap_const_lv32_FFFFFFC0));
end behav;
